//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#include <Core/RTTI/ReflectionContext.h>

#include <AssetBuilder/AssetFile.h>
#include <AssetBuilder/ModelProcessor.h>
#include <AssetBuilder/TextureProcessor.h>


namespace FE::AssetBuilder
{
    const Rtti::TypeID AssetFile::TypeID = Rtti::TypeID{
        0x19, 0x6d, 0x6b, 0x77, 0x48, 0x4f, 0x42, 0x9b, 0xa7, 0x4f, 0x0e, 0x99, 0xc4, 0xf3, 0x67, 0xb2,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_196d6b77484f429ba74f0e99c4f367b2()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& AssetFile::RTTI_GetType()
    {
        return RTTI_GetMutableType_196d6b77484f429ba74f0e99c4f367b2();
    }

    void AssetFile::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_196d6b77484f429ba74f0e99c4f367b2();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x19, 0x6d, 0x6b, 0x77, 0x48, 0x4f, 0x42, 0x9b,
            0xa7, 0x4f, 0x0e, 0x99, 0xc4, 0xf3, 0x67, 0xb2, // FE::AssetBuilder::AssetFile
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[4 * sizeof(Rtti::TypeID)] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_sourcePath
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_artifacts
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_builtArtifactIds
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_embeddedSourceData
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sourcePath = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_artifacts = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_builtArtifactIds = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_embeddedSourceData = {};

        static const festd::array<Rtti::FieldInfo, 4> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sourcePath",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &AssetFile::m_sourcePath,
                                                        kAttributes_m_sourcePath,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_artifacts",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &AssetFile::m_artifacts,
                                                        kAttributes_m_artifacts,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_builtArtifactIds",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &AssetFile::m_builtArtifactIds,
                                                        kAttributes_m_builtArtifactIds,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_embeddedSourceData",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 3 * sizeof(TypeID)),
                                                        &AssetFile::m_embeddedSourceData,
                                                        kAttributes_m_embeddedSourceData,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<AssetFile>(typeInstance,
                                        Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                        "FE::AssetBuilder::AssetFile",
                                        kBaseClassTypeIDs,
                                        kAttributes,
                                        kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_196d6b77484f429ba74f0e99c4f367b2(&AssetFile::Reflect);

    FE::Serialization::ResultCode AssetFile::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourcePath", m_sourcePath);
            object.Field("m_artifacts", m_artifacts);
            object.Field("m_builtArtifactIds", m_builtArtifactIds);
            object.Field("m_embeddedSourceData", m_embeddedSourceData);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode AssetFile::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourcePath", m_sourcePath);
            object.Field("m_artifacts", m_artifacts);
            object.Field("m_builtArtifactIds", m_builtArtifactIds);
            object.Field("m_embeddedSourceData", m_embeddedSourceData);
        }

        return context.GetResultCode();
    }

    uint64_t AssetFile::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x19, 0x6d, 0x6b, 0x77, 0x48, 0x4f, 0x42, 0x9b, 0xa7, 0x4f, 0x0e, 0x99, 0xc4, 0xf3, 0x67, 0xb2,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_sourcePath", 12);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_sourcePath)>());
            hasher.Update("m_artifacts", 11);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_artifacts)>());
            hasher.Update("m_builtArtifactIds", 18);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_builtArtifactIds)>());
            hasher.Update("m_embeddedSourceData", 20);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_embeddedSourceData)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t AssetFile::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder


namespace FE::AssetBuilder
{
    const Rtti::TypeID TextureBuildSettings::TypeID = Rtti::TypeID{
        0x38, 0xa7, 0xf2, 0x22, 0xc6, 0x36, 0x49, 0x47, 0xb7, 0x00, 0x9e, 0x6f, 0xa5, 0x82, 0xbc, 0x4a,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_38a7f222c6364947b7009e6fa582bc4a()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& TextureBuildSettings::RTTI_GetType()
    {
        return RTTI_GetMutableType_38a7f222c6364947b7009e6fa582bc4a();
    }

    void TextureBuildSettings::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_38a7f222c6364947b7009e6fa582bc4a();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x38, 0xa7, 0xf2, 0x22, 0xc6, 0x36, 0x49, 0x47,
            0xb7, 0x00, 0x9e, 0x6f, 0xa5, 0x82, 0xbc, 0x4a, // FE::AssetBuilder::TextureBuildSettings
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x33, 0x4f, 0x07, 0x50, 0x1b, 0x4e, 0x4f, 0x4c,
            0xac, 0x6f, 0x98, 0x53, 0x82, 0xd4, 0xbd, 0x11, // uint32_t m_sourceObjectIndex
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_sourcePath
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sourceObjectIndex = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sourcePath = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sourceObjectIndex",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &TextureBuildSettings::m_sourceObjectIndex,
                                                        kAttributes_m_sourceObjectIndex,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sourcePath",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &TextureBuildSettings::m_sourcePath,
                                                        kAttributes_m_sourcePath,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<TextureBuildSettings>(typeInstance,
                                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                   "FE::AssetBuilder::TextureBuildSettings",
                                                   kBaseClassTypeIDs,
                                                   kAttributes,
                                                   kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_38a7f222c6364947b7009e6fa582bc4a(&TextureBuildSettings::Reflect);

    FE::Serialization::ResultCode TextureBuildSettings::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
            object.Field("m_sourcePath", m_sourcePath);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode TextureBuildSettings::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
            object.Field("m_sourcePath", m_sourcePath);
        }

        return context.GetResultCode();
    }

    uint64_t TextureBuildSettings::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x38, 0xa7, 0xf2, 0x22, 0xc6, 0x36, 0x49, 0x47, 0xb7, 0x00, 0x9e, 0x6f, 0xa5, 0x82, 0xbc, 0x4a,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_sourceObjectIndex", 19);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_sourceObjectIndex)>());
            hasher.Update("m_sourcePath", 12);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_sourcePath)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t TextureBuildSettings::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder


namespace FE::AssetBuilder
{
    const Rtti::TypeID MeshBuildSettings::TypeID = Rtti::TypeID{
        0x53, 0x4c, 0xd6, 0x5c, 0x16, 0x45, 0x48, 0x4d, 0xb1, 0x24, 0x37, 0xe9, 0x08, 0x67, 0x6f, 0x00,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_534cd65c1645484db12437e908676f00()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MeshBuildSettings::RTTI_GetType()
    {
        return RTTI_GetMutableType_534cd65c1645484db12437e908676f00();
    }

    void MeshBuildSettings::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_534cd65c1645484db12437e908676f00();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x53, 0x4c, 0xd6, 0x5c, 0x16, 0x45, 0x48, 0x4d,
            0xb1, 0x24, 0x37, 0xe9, 0x08, 0x67, 0x6f, 0x00, // FE::AssetBuilder::MeshBuildSettings
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x33, 0x4f, 0x07, 0x50, 0x1b, 0x4e, 0x4f, 0x4c,
            0xac, 0x6f, 0x98, 0x53, 0x82, 0xd4, 0xbd, 0x11, // uint32_t m_sourceObjectIndex
            0xdd, 0x3b, 0xa9, 0xbb, 0xe7, 0xd2, 0x42, 0x17,
            0xa7, 0x97, 0xf7, 0xc8, 0x1e, 0xf3, 0x51, 0xa2, // bool m_generateLods
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sourceObjectIndex = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_generateLods = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sourceObjectIndex",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &MeshBuildSettings::m_sourceObjectIndex,
                                                        kAttributes_m_sourceObjectIndex,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_generateLods",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &MeshBuildSettings::m_generateLods,
                                                        kAttributes_m_generateLods,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<MeshBuildSettings>(typeInstance,
                                                Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                "FE::AssetBuilder::MeshBuildSettings",
                                                kBaseClassTypeIDs,
                                                kAttributes,
                                                kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_534cd65c1645484db12437e908676f00(&MeshBuildSettings::Reflect);

    FE::Serialization::ResultCode MeshBuildSettings::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
            object.Field("m_generateLods", m_generateLods);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode MeshBuildSettings::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
            object.Field("m_generateLods", m_generateLods);
        }

        return context.GetResultCode();
    }

    uint64_t MeshBuildSettings::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x53, 0x4c, 0xd6, 0x5c, 0x16, 0x45, 0x48, 0x4d, 0xb1, 0x24, 0x37, 0xe9, 0x08, 0x67, 0x6f, 0x00,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_sourceObjectIndex", 19);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_sourceObjectIndex)>());
            hasher.Update("m_generateLods", 14);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_generateLods)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t MeshBuildSettings::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder


namespace FE::AssetBuilder
{
    const Rtti::TypeID AssetFileArtifact::TypeID = Rtti::TypeID{
        0x5e, 0xc8, 0x9b, 0x68, 0x37, 0x2e, 0x43, 0x88, 0xbd, 0x0d, 0x86, 0x9c, 0x03, 0xc9, 0xc6, 0x5d,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_5ec89b68372e4388bd0d869c03c9c65d()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& AssetFileArtifact::RTTI_GetType()
    {
        return RTTI_GetMutableType_5ec89b68372e4388bd0d869c03c9c65d();
    }

    void AssetFileArtifact::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_5ec89b68372e4388bd0d869c03c9c65d();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x5e, 0xc8, 0x9b, 0x68, 0x37, 0x2e, 0x43, 0x88,
            0xbd, 0x0d, 0x86, 0x9c, 0x03, 0xc9, 0xc6, 0x5d, // FE::AssetBuilder::AssetFileArtifact
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[5 * sizeof(Rtti::TypeID)] = {
            0xa9, 0x08, 0x1c, 0xb4, 0x16, 0x14, 0x47, 0xe0, 0x9e,
            0x5d, 0xbc, 0x66, 0x7a, 0x52, 0x60, 0x21, // FE::Internal::StringImpl<FE::Internal::BasicStringImpl<FE::Internal::DefaultAllocatorStringStorage<FE::Internal::DynamicStringStorage>>> m_name
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_assetId
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_assetTypeId
            0xab, 0x67, 0xd9, 0xcb, 0x4c, 0x40, 0x44, 0xe8, 0x8c,
            0x75, 0xb6, 0x7b, 0x46, 0xb1, 0xb8, 0x68, // FE::Rtti::Any m_buildSettings
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_dependencies
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_name = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_assetId = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_assetTypeId = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_buildSettings = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_dependencies = {};

        static const festd::array<Rtti::FieldInfo, 5> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_name",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &AssetFileArtifact::m_name,
                                                        kAttributes_m_name,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_assetId",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &AssetFileArtifact::m_assetId,
                                                        kAttributes_m_assetId,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_assetTypeId",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &AssetFileArtifact::m_assetTypeId,
                                                        kAttributes_m_assetTypeId,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_buildSettings",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 3 * sizeof(TypeID)),
                                                        &AssetFileArtifact::m_buildSettings,
                                                        kAttributes_m_buildSettings,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_dependencies",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 4 * sizeof(TypeID)),
                                                        &AssetFileArtifact::m_dependencies,
                                                        kAttributes_m_dependencies,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<AssetFileArtifact>(typeInstance,
                                                Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                "FE::AssetBuilder::AssetFileArtifact",
                                                kBaseClassTypeIDs,
                                                kAttributes,
                                                kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_5ec89b68372e4388bd0d869c03c9c65d(&AssetFileArtifact::Reflect);

    FE::Serialization::ResultCode AssetFileArtifact::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_name", m_name);
            object.Field("m_assetId", m_assetId);
            object.Field("m_assetTypeId", m_assetTypeId);
            object.Field("m_buildSettings", m_buildSettings);
            object.Field("m_dependencies", m_dependencies);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode AssetFileArtifact::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_name", m_name);
            object.Field("m_assetId", m_assetId);
            object.Field("m_assetTypeId", m_assetTypeId);
            object.Field("m_buildSettings", m_buildSettings);
            object.Field("m_dependencies", m_dependencies);
        }

        return context.GetResultCode();
    }

    uint64_t AssetFileArtifact::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x5e, 0xc8, 0x9b, 0x68, 0x37, 0x2e, 0x43, 0x88, 0xbd, 0x0d, 0x86, 0x9c, 0x03, 0xc9, 0xc6, 0x5d,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_name", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_name)>());
            hasher.Update("m_assetId", 9);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_assetId)>());
            hasher.Update("m_assetTypeId", 13);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_assetTypeId)>());
            hasher.Update("m_buildSettings", 15);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_buildSettings)>());
            hasher.Update("m_dependencies", 14);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_dependencies)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t AssetFileArtifact::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder


namespace FE::AssetBuilder
{
    const Rtti::TypeID AssetFileDependency::TypeID = Rtti::TypeID{
        0x7c, 0x65, 0x43, 0xf2, 0x90, 0xa8, 0x45, 0xf5, 0xb9, 0x3d, 0xc7, 0x60, 0x60, 0x6b, 0x31, 0x32,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_7c6543f290a845f5b93dc760606b3132()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& AssetFileDependency::RTTI_GetType()
    {
        return RTTI_GetMutableType_7c6543f290a845f5b93dc760606b3132();
    }

    void AssetFileDependency::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_7c6543f290a845f5b93dc760606b3132();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x7c, 0x65, 0x43, 0xf2, 0x90, 0xa8, 0x45, 0xf5,
            0xb9, 0x3d, 0xc7, 0x60, 0x60, 0x6b, 0x31, 0x32, // FE::AssetBuilder::AssetFileDependency
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[3 * sizeof(Rtti::TypeID)] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_assetId
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_expectedTypeId
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_kind
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_assetId = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_expectedTypeId = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_kind = {};

        static const festd::array<Rtti::FieldInfo, 3> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_assetId",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &AssetFileDependency::m_assetId,
                                                        kAttributes_m_assetId,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_expectedTypeId",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &AssetFileDependency::m_expectedTypeId,
                                                        kAttributes_m_expectedTypeId,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_kind",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &AssetFileDependency::m_kind,
                                                        kAttributes_m_kind,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<AssetFileDependency>(typeInstance,
                                                  Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                  "FE::AssetBuilder::AssetFileDependency",
                                                  kBaseClassTypeIDs,
                                                  kAttributes,
                                                  kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_7c6543f290a845f5b93dc760606b3132(&AssetFileDependency::Reflect);

    FE::Serialization::ResultCode AssetFileDependency::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_assetId", m_assetId);
            object.Field("m_expectedTypeId", m_expectedTypeId);
            object.Field("m_kind", m_kind);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode AssetFileDependency::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_assetId", m_assetId);
            object.Field("m_expectedTypeId", m_expectedTypeId);
            object.Field("m_kind", m_kind);
        }

        return context.GetResultCode();
    }

    uint64_t AssetFileDependency::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x7c, 0x65, 0x43, 0xf2, 0x90, 0xa8, 0x45, 0xf5, 0xb9, 0x3d, 0xc7, 0x60, 0x60, 0x6b, 0x31, 0x32,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_assetId", 9);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_assetId)>());
            hasher.Update("m_expectedTypeId", 16);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_expectedTypeId)>());
            hasher.Update("m_kind", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_kind)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t AssetFileDependency::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder


namespace FE::AssetBuilder
{
    const Rtti::TypeID ModelBuildSettings::TypeID = Rtti::TypeID{
        0x80, 0xd1, 0xa4, 0x92, 0x1c, 0x42, 0x4c, 0x3c, 0x99, 0x13, 0xdf, 0x80, 0x85, 0xe9, 0x65, 0x5a,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_80d1a4921c424c3c9913df8085e9655a()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ModelBuildSettings::RTTI_GetType()
    {
        return RTTI_GetMutableType_80d1a4921c424c3c9913df8085e9655a();
    }

    void ModelBuildSettings::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_80d1a4921c424c3c9913df8085e9655a();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x80, 0xd1, 0xa4, 0x92, 0x1c, 0x42, 0x4c, 0x3c,
            0x99, 0x13, 0xdf, 0x80, 0x85, 0xe9, 0x65, 0x5a, // FE::AssetBuilder::ModelBuildSettings
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x33, 0x4f, 0x07, 0x50, 0x1b, 0x4e, 0x4f, 0x4c,
            0xac, 0x6f, 0x98, 0x53, 0x82, 0xd4, 0xbd, 0x11, // uint32_t m_sourceObjectIndex
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sourceObjectIndex = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sourceObjectIndex",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &ModelBuildSettings::m_sourceObjectIndex,
                                                        kAttributes_m_sourceObjectIndex,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<ModelBuildSettings>(typeInstance,
                                                 Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                 "FE::AssetBuilder::ModelBuildSettings",
                                                 kBaseClassTypeIDs,
                                                 kAttributes,
                                                 kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_80d1a4921c424c3c9913df8085e9655a(&ModelBuildSettings::Reflect);

    FE::Serialization::ResultCode ModelBuildSettings::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode ModelBuildSettings::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_sourceObjectIndex", m_sourceObjectIndex);
        }

        return context.GetResultCode();
    }

    uint64_t ModelBuildSettings::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x80, 0xd1, 0xa4, 0x92, 0x1c, 0x42, 0x4c, 0x3c, 0x99, 0x13, 0xdf, 0x80, 0x85, 0xe9, 0x65, 0x5a,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_sourceObjectIndex", 19);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_sourceObjectIndex)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t ModelBuildSettings::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::AssetBuilder
