//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>
{% for include in table.includes %}
{{ include }}
{% endfor %}
namespace FE::Graphics
{
    struct {{ table.name }} final
    {
        static constexpr uint32_t kElementCountPerPage = {{ table.element_count_per_page }};
        {% for name, offset in table.offsets.items() %}
        static constexpr uint32_t kOffset_{{ name }} = {{ offset }};
        {%- endfor %}

        struct Row final
        {
            {%- for column in table.columns %}
            DB::ElementHandle<{{ column.typename }}, kOffset_{{ column.name }}> {{ column.name }};
            {%- endfor %}
        };

        struct RWRow final
        {
            {%- for column in table.columns %}
            DB::RWElementHandle<{{ column.typename }}, kOffset_{{ column.name }}> {{ column.name }};
            {%- endfor %}
        };

        struct Instance final : public DB::TableBase
        {
            Instance(DB::Database* database, const uint32_t globalID)
                : TableBase(database, globalID)
            {
            }

            Row ReadRow(const uint32_t rowIndex)
            {
                const uint32_t pageIndex = rowIndex / kElementCountPerPage;
                const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

                const DB::StoragePage* page = m_pages[pageIndex];
                const std::byte* storage = page->GetHostStorage();

                Row row;
                {%- for column in table.columns %}
                row.{{ column.name }}.Setup(storage, localRowIndex);
                {%- endfor %}
                return row;
            }

            Row ReadRow(const DB::Ref<{{ table.name }}> reference)
            {
                return ReadRow(reference.m_rowIndex);
            }

            RWRow WriteRow(const uint32_t rowIndex)
            {
                const uint32_t pageIndex = rowIndex / kElementCountPerPage;
                const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

                DB::StoragePage* page = m_pages[pageIndex];
                std::byte* storage = page->GetHostStorage();

                RWRow row;
                {%- for column in table.columns %}
                row.{{ column.name }}.Setup(storage, localRowIndex);
                {%- endfor %}
                return row;
            }

            RWRow WriteRow(const DB::Ref<{{ table.name }}> reference)
            {
                return WriteRow(reference.m_rowIndex);
            }
        };
    };
}
