#pragma once
#include <Core/Math/Transform.h>
#include <Framework/Entities/EntityComponentRegistry.h>

namespace FE::GameFramework
{
    //! @brief Authored local translation, rotation, and uniform scale relative to the immediate transform parent.
    struct TransformComponent final
    {
        //! @brief Local transform; changes flow through entity command replacement.
        Transform m_local = Transform::Identity();
        FE_RTTI_Reflect("a8cdb00d-20ce-4780-b08d-211d0f600001");
        FE_RTTI_Serialize();
    };


    //! @brief Optional authored scale modifier applied before the local transform.
    struct NonUniformScaleComponent final
    {
        //! @brief Per-axis local scale, defaulting to one.
        Vector3 m_scale{ 1.0f, 1.0f, 1.0f };
        FE_RTTI_Reflect("a8cdb00d-20ce-4780-b08d-211d0f600002");
        FE_RTTI_Serialize();
    };


    //! @brief Transient world matrix generated by TransformationSystem, including inherited scale.
    struct WorldTransformComponent final
    {
        //! @brief Latest published local-to-world matrix; never serialized as authored content.
        Matrix4x4 m_world = Matrix4x4::kIdentity;
        FE_RTTI_Reflect("a8cdb00d-20ce-4780-b08d-211d0f600003");
    };
} // namespace FE::GameFramework
