//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once

namespace FE
{
    //! @brief Retain CoreTests's generated reflection in statically linked programs.
    void CallLinkerAnchor_CoreTests();
} // namespace FE
