//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#include <Core/RTTI/ReflectionContext.h>

#include <FerrumCli/CommandLine.h>


namespace FE::FerrumCli
{
    const Rtti::TypeID CommandLineParser::TypeID = Rtti::TypeID{
        0x2b, 0x40, 0x9c, 0xcd, 0x3c, 0xa4, 0x46, 0xa0, 0xba, 0x21, 0x48, 0xb1, 0xd9, 0x2a, 0xed, 0x2b,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_2b409ccd3ca446a0ba2148b1d92aed2b(CommandLineParser* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x2b, 0x40, 0x9c, 0xcd, 0x3c, 0xa4, 0x46, 0xa0,
                0xba, 0x21, 0x48, 0xb1, 0xd9, 0x2a, 0xed, 0x2b, // FE::FerrumCli::CommandLineParser (this type)
                0xc3, 0xc4, 0x96, 0x54, 0xfe, 0x98, 0x4c, 0xe6,
                0xb7, 0x59, 0x06, 0xd7, 0xef, 0x4e, 0xaa, 0x0f, // FE::Cli::Parser
                0x01, 0xdd, 0xd1, 0x16, 0xd0, 0x90, 0x49, 0xe4,
                0x98, 0xb9, 0x41, 0x00, 0xcf, 0xb5, 0x05, 0x09, // FE::Cli::Command
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Cli::Parser*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Cli::Command*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_2b409ccd3ca446a0ba2148b1d92aed2b()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& CommandLineParser::RTTI_GetType()
    {
        return RTTI_GetMutableType_2b409ccd3ca446a0ba2148b1d92aed2b();
    }

    void* FE_VECTORCALL CommandLineParser::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_2b409ccd3ca446a0ba2148b1d92aed2b(this, typeID);
    }

    const void* FE_VECTORCALL CommandLineParser::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_2b409ccd3ca446a0ba2148b1d92aed2b(const_cast<CommandLineParser*>(this), typeID);
    }

    void CommandLineParser::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_2b409ccd3ca446a0ba2148b1d92aed2b();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x2b, 0x40, 0x9c, 0xcd, 0x3c, 0xa4, 0x46, 0xa0,
            0xba, 0x21, 0x48, 0xb1, 0xd9, 0x2a, 0xed, 0x2b, // FE::FerrumCli::CommandLineParser
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xc3, 0xc4, 0x96, 0x54, 0xfe, 0x98, 0x4c, 0xe6, 0xb7, 0x59, 0x06, 0xd7, 0xef, 0x4e, 0xaa, 0x0f, // FE::Cli::Parser
            0x01, 0xdd, 0xd1, 0x16, 0xd0, 0x90, 0x49, 0xe4, 0x98, 0xb9, 0x41, 0x00, 0xcf, 0xb5, 0x05, 0x09, // FE::Cli::Command
        };
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x9f, 0xf5, 0x6e, 0x68, 0x87, 0x57, 0x43, 0xe2,
            0x88, 0x26, 0xac, 0xf3, 0x41, 0x9f, 0x16, 0xfd, // FE::Cli::Flag m_help
            0x9f, 0xf5, 0x6e, 0x68, 0x87, 0x57, 0x43, 0xe2,
            0x88, 0x26, 0xac, 0xf3, 0x41, 0x9f, 0x16, 0xfd, // FE::Cli::Flag m_version
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 1> kAttributes_m_help = {
            Rtti::Attribute{ .m_key = "Cli::Description", .m_value = "Print this help message" },

        };

        static constexpr festd::array<Rtti::Attribute, 1> kAttributes_m_version = {
            Rtti::Attribute{ .m_key = "Cli::Description", .m_value = "Print version" },

        };

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_help",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &CommandLineParser::m_help,
                                                        kAttributes_m_help,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_version",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &CommandLineParser::m_version,
                                                        kAttributes_m_version,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<CommandLineParser>(typeInstance,
                                                Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                "FE::FerrumCli::CommandLineParser",
                                                kBaseClassTypeIDs,
                                                kAttributes,
                                                kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_2b409ccd3ca446a0ba2148b1d92aed2b(&CommandLineParser::Reflect);
} // namespace FE::FerrumCli


namespace FE::FerrumCli
{
    const Rtti::TypeID Build::TypeID = Rtti::TypeID{
        0x4d, 0x10, 0x5b, 0x8d, 0x0e, 0x84, 0x46, 0x0b, 0x98, 0xbc, 0x8a, 0x4c, 0x37, 0x10, 0xa1, 0x93,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_4d105b8d0e84460b98bc8a4c3710a193(Build* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x4d, 0x10, 0x5b, 0x8d, 0x0e, 0x84, 0x46, 0x0b,
                0x98, 0xbc, 0x8a, 0x4c, 0x37, 0x10, 0xa1, 0x93, // FE::FerrumCli::Build (this type)
                0x0f, 0x01, 0xe8, 0x27, 0xc9, 0xd9, 0x43, 0xf0,
                0x89, 0x69, 0x47, 0xbf, 0x6d, 0x03, 0x5b, 0x82, // FE::Cli::Subcommand
                0x01, 0xdd, 0xd1, 0x16, 0xd0, 0x90, 0x49, 0xe4,
                0x98, 0xb9, 0x41, 0x00, 0xcf, 0xb5, 0x05, 0x09, // FE::Cli::Command
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Cli::Subcommand*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Cli::Command*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_4d105b8d0e84460b98bc8a4c3710a193()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }

        void RTTI_DefaultConstruct_4d105b8d0e84460b98bc8a4c3710a193(void* storage)
        {
            ::new (storage) Build();
        }
    } // namespace

    const Rtti::Type& Build::RTTI_GetType()
    {
        return RTTI_GetMutableType_4d105b8d0e84460b98bc8a4c3710a193();
    }

    void* FE_VECTORCALL Build::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_4d105b8d0e84460b98bc8a4c3710a193(this, typeID);
    }

    const void* FE_VECTORCALL Build::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_4d105b8d0e84460b98bc8a4c3710a193(const_cast<Build*>(this), typeID);
    }

    void Build::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_4d105b8d0e84460b98bc8a4c3710a193();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x4d, 0x10, 0x5b, 0x8d, 0x0e, 0x84, 0x46, 0x0b,
            0x98, 0xbc, 0x8a, 0x4c, 0x37, 0x10, 0xa1, 0x93, // FE::FerrumCli::Build
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x0f, 0x01, 0xe8, 0x27, 0xc9, 0xd9, 0x43, 0xf0, 0x89, 0x69, 0x47, 0xbf, 0x6d, 0x03, 0x5b, 0x82, // FE::Cli::Subcommand
            0x01, 0xdd, 0xd1, 0x16, 0xd0, 0x90, 0x49, 0xe4, 0x98, 0xb9, 0x41, 0x00, 0xcf, 0xb5, 0x05, 0x09, // FE::Cli::Command
        };
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x9f, 0xf5, 0x6e, 0x68, 0x87, 0x57, 0x43, 0xe2,
            0x88, 0x26, 0xac, 0xf3, 0x41, 0x9f, 0x16, 0xfd, // FE::Cli::Flag m_help
            0x30, 0x1b, 0xc2, 0x48, 0xff, 0x31, 0x43, 0xdb,
            0xb2, 0x85, 0x92, 0x66, 0x23, 0xb3, 0x32, 0x6f, // FE::Cli::Option m_asset
        };
        static constexpr festd::array<Rtti::Attribute, 2> kAttributes = {
            Rtti::Attribute{ .m_key = "Cli::Parent", .m_value = "FE::FerrumCli::CommandLineParser" },
            Rtti::Attribute{ .m_key = "Cli::Description", .m_value = "Build an asset" },
        };

        static constexpr festd::array<Rtti::Attribute, 1> kAttributes_m_help = {
            Rtti::Attribute{ .m_key = "Cli::Description", .m_value = "Print this help message" },

        };

        static constexpr festd::array<Rtti::Attribute, 2> kAttributes_m_asset = {
            Rtti::Attribute{ .m_key = "Cli::Description", .m_value = "Asset to build" },

            Rtti::Attribute{ .m_key = "Cli::ValueName", .m_value = "path" },

        };

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_help",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &Build::m_help,
                                                        kAttributes_m_help,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_asset",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &Build::m_asset,
                                                        kAttributes_m_asset,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Build>(typeInstance,
                                    Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                    "FE::FerrumCli::Build",
                                    kBaseClassTypeIDs,
                                    kAttributes,
                                    kFields,
                                    nullptr,
                                    &RTTI_DefaultConstruct_4d105b8d0e84460b98bc8a4c3710a193);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_4d105b8d0e84460b98bc8a4c3710a193(&Build::Reflect);
} // namespace FE::FerrumCli
