//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once

namespace FE::Graphics
{
    struct MeshLodInfoTable;
    struct MeshGroupTable;
    struct MeshInstanceTable;
} // namespace FE::Graphics
