//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

namespace FE::Graphics
{
    struct MaterialInstanceTable final : public DB::TableBase
    {
        FE_RTTI("DA93720C-B6A5-58C2-9859-E0A2BB3CA5F8");

        static constexpr uint32_t kRowsPerPage = DB::kTablePageSize / (sizeof(BufferPointer));

        static constexpr uint32_t kOffset_m_materialParameters = 0;

        static_assert(kRowsPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<BufferPointer, kOffset_m_materialParameters> m_materialParameters;
        };

        struct RWRow final
        {
            DB::RWElementHandle<BufferPointer, kOffset_m_materialParameters> m_materialParameters;
        };

        using Instance = BufferPointer;

        MaterialInstanceTable(DB::Database* database)
            : TableBase(database, kRowsPerPage)
        {
        }

        void DoRelease() override
        {
            Memory::DefaultDelete(this);
        }

        [[nodiscard]] DB::Ref<MaterialInstanceTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_materialParameters.Construct();
            return DB::Ref<MaterialInstanceTable>{ rowIndex };
        }

        [[nodiscard]] DB::Slice<MaterialInstanceTable> AllocateRows(const uint32_t rowCount)
        {
            const RowRangeHandle range = AllocateRowsUninitialized(rowCount);
            FE_AssertDebug(range.m_size == rowCount);
            for (uint32_t rowIndex = 0; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_materialParameters.Construct();
            }

            return DB::Slice<MaterialInstanceTable>{ range.m_offset, range.m_size };
        }

        void Free(const DB::Ref<MaterialInstanceTable> row)
        {
            TableBase::Free(row.m_rowIndex);
        }

        void Free(const DB::Slice<MaterialInstanceTable> rows)
        {
            TableBase::Free(RowRangeHandle{ rows.m_rowIndex, rows.m_count });
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_materialParameters.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MaterialInstanceTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_materialParameters.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MaterialInstanceTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }

        void CopyColumn(const DB::Slice<MaterialInstanceTable> destination, const festd::span<const BufferPointer> source)
        {
            FE_Assert(destination.m_count == source.size());

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(pageIndex == (destination.m_rowIndex + destination.m_count - 1) / kRowsPerPage,
                      "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            auto* destinationData = reinterpret_cast<BufferPointer*>(storage + kOffset_m_materialParameters) + localRowIndex;
            festd::copy(source, destinationData);
        }
    };
} // namespace FE::Graphics
