//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

#include <Graphics/Core/Meshlet.h>

namespace FE::Graphics
{
    struct MeshLodInfoTable final : public DB::TableBase
    {
        FE_RTTI("429A06B5-0BEB-5171-87F8-18737671FB7F");

        static constexpr uint32_t kElementCountPerPage = DB::kTablePageSize / (sizeof(Core::MeshLodInfo));

        static constexpr uint32_t kOffset_m_info = 0;

        static_assert(kElementCountPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<Core::MeshLodInfo, kOffset_m_info> m_info;
        };

        struct RWRow final
        {
            DB::RWElementHandle<Core::MeshLodInfo, kOffset_m_info> m_info;
        };

        using Instance = BufferPointer;

        MeshLodInfoTable(DB::Database* database)
            : TableBase(database, kElementCountPerPage)
        {
        }

        [[nodiscard]] DB::Ref<MeshLodInfoTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_info.Construct();
            return DB::Ref<MeshLodInfoTable>{ rowIndex };
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_info.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshLodInfoTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_info.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshLodInfoTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }
    };
} // namespace FE::Graphics
