//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

#include <Graphics/Core/Meshlet.h>

namespace FE::Graphics
{
    struct MeshGroupTable final : public DB::TableBase
    {
        FE_RTTI("03321E1E-0A92-5203-B75C-027838609287");

        static constexpr uint32_t kRowsPerPage = DB::kTablePageSize
            / (sizeof(BufferPointer) + sizeof(DB::Slice<MeshLodInfoTable>) + sizeof(DB::Ref<MaterialInstanceTable>)
               + sizeof(Core::MeshBoundsInfo) + sizeof(uint32_t));

        static constexpr uint32_t kOffset_m_geometry = 0;
        static constexpr uint32_t kOffset_m_lods = kOffset_m_geometry + sizeof(BufferPointer) * kRowsPerPage;
        static constexpr uint32_t kOffset_m_materialInstance =
            kOffset_m_lods + sizeof(DB::Slice<MeshLodInfoTable>) * kRowsPerPage;
        static constexpr uint32_t kOffset_m_bounds =
            kOffset_m_materialInstance + sizeof(DB::Ref<MaterialInstanceTable>) * kRowsPerPage;
        static constexpr uint32_t kOffset_m_renderable = kOffset_m_bounds + sizeof(Core::MeshBoundsInfo) * kRowsPerPage;

        static_assert(kRowsPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<BufferPointer, kOffset_m_geometry> m_geometry;
            DB::ElementHandle<DB::Slice<MeshLodInfoTable>, kOffset_m_lods> m_lods;
            DB::ElementHandle<DB::Ref<MaterialInstanceTable>, kOffset_m_materialInstance> m_materialInstance;
            DB::ElementHandle<Core::MeshBoundsInfo, kOffset_m_bounds> m_bounds;
            DB::ElementHandle<uint32_t, kOffset_m_renderable> m_renderable;
        };

        struct RWRow final
        {
            DB::RWElementHandle<BufferPointer, kOffset_m_geometry> m_geometry;
            DB::RWElementHandle<DB::Slice<MeshLodInfoTable>, kOffset_m_lods> m_lods;
            DB::RWElementHandle<DB::Ref<MaterialInstanceTable>, kOffset_m_materialInstance> m_materialInstance;
            DB::RWElementHandle<Core::MeshBoundsInfo, kOffset_m_bounds> m_bounds;
            DB::RWElementHandle<uint32_t, kOffset_m_renderable> m_renderable;
        };

        using Instance = BufferPointer;

        MeshGroupTable(DB::Database* database)
            : TableBase(database, kRowsPerPage)
        {
        }

        void DoRelease() override
        {
            Memory::DefaultDelete(this);
        }

        [[nodiscard]] DB::Ref<MeshGroupTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_geometry.Construct();
            row.m_lods.Construct();
            row.m_materialInstance.Construct();
            row.m_bounds.Construct();
            row.m_renderable.Construct();
            return DB::Ref<MeshGroupTable>{ rowIndex };
        }

        [[nodiscard]] DB::Slice<MeshGroupTable> AllocateRows(const uint32_t rowCount)
        {
            const RowRangeHandle range = AllocateRowsUninitialized(rowCount);
            FE_AssertDebug(range.m_size == rowCount);
            for (uint32_t rowIndex = 0; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_geometry.Construct();
                row.m_lods.Construct();
                row.m_materialInstance.Construct();
                row.m_bounds.Construct();
                row.m_renderable.Construct();
            }

            return DB::Slice<MeshGroupTable>{ range.m_offset, range.m_size };
        }

        [[nodiscard]] bool TryReallocateRows(DB::Slice<MeshGroupTable>& rows, const uint32_t rowCount)
        {
            RowRangeHandle range{ rows.m_rowIndex, rows.m_count };
            if (!TryReallocateRowsUninitialized(range, rowCount))
                return false;

            for (uint32_t rowIndex = rows.m_count; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_geometry.Construct();
                row.m_lods.Construct();
                row.m_materialInstance.Construct();
                row.m_bounds.Construct();
                row.m_renderable.Construct();
            }

            rows = { range.m_offset, range.m_size };
            return true;
        }

        void Free(const DB::Ref<MeshGroupTable> row)
        {
            TableBase::Free(row.m_rowIndex);
        }

        void Free(const DB::Slice<MeshGroupTable> rows)
        {
            TableBase::Free(RowRangeHandle{ rows.m_rowIndex, rows.m_count });
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_geometry.Setup(storage, localRowIndex);
            row.m_lods.Setup(storage, localRowIndex);
            row.m_materialInstance.Setup(storage, localRowIndex);
            row.m_bounds.Setup(storage, localRowIndex);
            row.m_renderable.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshGroupTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_geometry.Setup(storage, localRowIndex);
            row.m_lods.Setup(storage, localRowIndex);
            row.m_materialInstance.Setup(storage, localRowIndex);
            row.m_bounds.Setup(storage, localRowIndex);
            row.m_renderable.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshGroupTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }

        void CopyColumn(const DB::Slice<MeshGroupTable> destination, const festd::span<const BufferPointer> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData = reinterpret_cast<BufferPointer*>(storage + kOffset_m_geometry) + localRowIndex;
            festd::copy(source, destinationData);
        }

        void CopyColumn(const DB::Slice<MeshGroupTable> destination, const festd::span<const DB::Slice<MeshLodInfoTable>> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData = reinterpret_cast<DB::Slice<MeshLodInfoTable>*>(storage + kOffset_m_lods) + localRowIndex;
            festd::copy(source, destinationData);
        }

        void CopyColumn(const DB::Slice<MeshGroupTable> destination,
                        const festd::span<const DB::Ref<MaterialInstanceTable>> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData =
                reinterpret_cast<DB::Ref<MaterialInstanceTable>*>(storage + kOffset_m_materialInstance) + localRowIndex;
            festd::copy(source, destinationData);
        }

        void CopyColumn(const DB::Slice<MeshGroupTable> destination, const festd::span<const Core::MeshBoundsInfo> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData = reinterpret_cast<Core::MeshBoundsInfo*>(storage + kOffset_m_bounds) + localRowIndex;
            festd::copy(source, destinationData);
        }

        void CopyColumn(const DB::Slice<MeshGroupTable> destination, const festd::span<const uint32_t> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData = reinterpret_cast<uint32_t*>(storage + kOffset_m_renderable) + localRowIndex;
            festd::copy(source, destinationData);
        }
    };
} // namespace FE::Graphics
