//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once

#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

namespace FE::Graphics
{
    struct MeshGroupTable final : public DB::TableBase
    {
        static constexpr uint32_t kElementCountPerPage =
            DB::kTablePageSize / (sizeof(BufferPointer) + sizeof(DB::Slice<MeshLodInfoTable>));

        static constexpr uint32_t kOffset_m_geometry = 0;
        static constexpr uint32_t kOffset_m_lods = kOffset_m_geometry + sizeof(BufferPointer) * kElementCountPerPage;

        static_assert(kElementCountPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<BufferPointer, kOffset_m_geometry> m_geometry;
            DB::ElementHandle<DB::Slice<MeshLodInfoTable>, kOffset_m_lods> m_lods;
        };

        struct RWRow final
        {
            DB::RWElementHandle<BufferPointer, kOffset_m_geometry> m_geometry;
            DB::RWElementHandle<DB::Slice<MeshLodInfoTable>, kOffset_m_lods> m_lods;
        };

        using Instance = BufferPointer;

        MeshGroupTable(DB::Database* database, const uint32_t globalID)
            : TableBase(database, globalID, kElementCountPerPage)
        {
        }

        [[nodiscard]] DB::Ref<MeshGroupTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_geometry.Construct();
            row.m_lods.Construct();
            return DB::Ref<MeshGroupTable>{ rowIndex };
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_geometry.Setup(storage, localRowIndex);
            row.m_lods.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshGroupTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_geometry.Setup(storage, localRowIndex);
            row.m_lods.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshGroupTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }
    };
} // namespace FE::Graphics
