//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once

#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

#include <FeCore/Math/Sphere.h>

namespace FE::Graphics
{
    struct MeshInstanceTable final : public DB::TableBase
    {
        static constexpr uint32_t kElementCountPerPage =
            DB::kTablePageSize / (sizeof(DB::Ref<MeshGroupTable>) + sizeof(float4x4));

        static constexpr uint32_t kOffset_m_meshGroup = 0;
        static constexpr uint32_t kOffset_m_transform =
            kOffset_m_meshGroup + sizeof(DB::Ref<MeshGroupTable>) * kElementCountPerPage;

        static_assert(kElementCountPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<DB::Ref<MeshGroupTable>, kOffset_m_meshGroup> m_meshGroup;
            DB::ElementHandle<float4x4, kOffset_m_transform> m_transform;
        };

        struct RWRow final
        {
            DB::RWElementHandle<DB::Ref<MeshGroupTable>, kOffset_m_meshGroup> m_meshGroup;
            DB::RWElementHandle<float4x4, kOffset_m_transform> m_transform;
        };

        using Instance = BufferPointer;

        MeshInstanceTable(DB::Database* database, const uint32_t globalID)
            : TableBase(database, globalID, kElementCountPerPage)
        {
        }

        [[nodiscard]] DB::Ref<MeshInstanceTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_meshGroup.Construct();
            row.m_transform.Construct();
            return DB::Ref<MeshInstanceTable>{ rowIndex };
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_meshGroup.Setup(storage, localRowIndex);
            row.m_transform.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshInstanceTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kElementCountPerPage;
            const uint32_t localRowIndex = rowIndex % kElementCountPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_meshGroup.Setup(storage, localRowIndex);
            row.m_transform.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshInstanceTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }
    };
} // namespace FE::Graphics
