//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

namespace FE::Graphics
{
    struct MeshInstanceTable final : public DB::TableBase
    {
        FE_RTTI("8A836070-A798-50FB-A93B-6FE5848B70B9");

        static constexpr uint32_t kRowsPerPage = DB::kTablePageSize / (sizeof(DB::Ref<MeshGroupTable>) + sizeof(float4x4));

        static constexpr uint32_t kOffset_m_meshGroup = 0;
        static constexpr uint32_t kOffset_m_transform = kOffset_m_meshGroup + sizeof(DB::Ref<MeshGroupTable>) * kRowsPerPage;

        static_assert(kRowsPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<DB::Ref<MeshGroupTable>, kOffset_m_meshGroup> m_meshGroup;
            DB::ElementHandle<float4x4, kOffset_m_transform> m_transform;
        };

        struct RWRow final
        {
            DB::RWElementHandle<DB::Ref<MeshGroupTable>, kOffset_m_meshGroup> m_meshGroup;
            DB::RWElementHandle<float4x4, kOffset_m_transform> m_transform;
        };

        using Instance = BufferPointer;

        MeshInstanceTable(DB::Database* database)
            : TableBase(database, kRowsPerPage)
        {
        }

        [[nodiscard]] DB::Ref<MeshInstanceTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_meshGroup.Construct();
            row.m_transform.Construct();
            return DB::Ref<MeshInstanceTable>{ rowIndex };
        }

        [[nodiscard]] DB::Slice<MeshInstanceTable> AllocateRows(const uint32_t rowCount)
        {
            const RowRangeHandle range = AllocateRowsUninitialized(rowCount);
            FE_AssertDebug(range.m_size == rowCount);
            for (uint32_t rowIndex = 0; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_meshGroup.Construct();
                row.m_transform.Construct();
            }

            return DB::Slice<MeshInstanceTable>{ range.m_offset, range.m_size };
        }

        void Free(const DB::Ref<MeshInstanceTable> row)
        {
            TableBase::Free(row.m_rowIndex);
        }

        void Free(const DB::Slice<MeshInstanceTable> rows)
        {
            TableBase::Free(RowRangeHandle{ rows.m_rowIndex, rows.m_count });
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_meshGroup.Setup(storage, localRowIndex);
            row.m_transform.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshInstanceTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_meshGroup.Setup(storage, localRowIndex);
            row.m_transform.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshInstanceTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }

        void CopyColumn(const DB::Slice<MeshInstanceTable> destination, const festd::span<const DB::Ref<MeshGroupTable>> source)
        {
            FE_Assert(destination.m_count == source.size());

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(pageIndex == (destination.m_rowIndex + destination.m_count - 1) / kRowsPerPage,
                      "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            auto* destinationData = reinterpret_cast<DB::Ref<MeshGroupTable>*>(storage + kOffset_m_meshGroup) + localRowIndex;
            festd::copy(source, destinationData);
        }

        void CopyColumn(const DB::Slice<MeshInstanceTable> destination, const festd::span<const float4x4> source)
        {
            FE_Assert(destination.m_count == source.size());

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(pageIndex == (destination.m_rowIndex + destination.m_count - 1) / kRowsPerPage,
                      "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            auto* destinationData = reinterpret_cast<float4x4*>(storage + kOffset_m_transform) + localRowIndex;
            festd::copy(source, destinationData);
        }
    };
} // namespace FE::Graphics
