//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Graphics/Database/Database.h>
#include <Graphics/Tables/Forwards.h>

namespace FE::Graphics
{
    struct MeshMemberTable final : public DB::TableBase
    {
        FE_RTTI("10AD85C9-459C-570C-B6ED-5813E489B160");

        static constexpr uint32_t kRowsPerPage = DB::kTablePageSize / (sizeof(DB::Ref<MeshInstanceTable>));

        static constexpr uint32_t kOffset_m_instance = 0;

        static_assert(kRowsPerPage > 0);

        struct Row final
        {
            DB::ElementHandle<DB::Ref<MeshInstanceTable>, kOffset_m_instance> m_instance;
        };

        struct RWRow final
        {
            DB::RWElementHandle<DB::Ref<MeshInstanceTable>, kOffset_m_instance> m_instance;
        };

        using Instance = BufferPointer;

        MeshMemberTable(DB::Database* database)
            : TableBase(database, kRowsPerPage)
        {
        }

        void DoRelease() override
        {
            Memory::DefaultDelete(this);
        }

        [[nodiscard]] DB::Ref<MeshMemberTable> AllocateRow()
        {
            const uint32_t rowIndex = AllocateRowUninitialized();
            const RWRow row = WriteRow(rowIndex);
            row.m_instance.Construct();
            return DB::Ref<MeshMemberTable>{ rowIndex };
        }

        [[nodiscard]] DB::Slice<MeshMemberTable> AllocateRows(const uint32_t rowCount)
        {
            const RowRangeHandle range = AllocateRowsUninitialized(rowCount);
            FE_AssertDebug(range.m_size == rowCount);
            for (uint32_t rowIndex = 0; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_instance.Construct();
            }

            return DB::Slice<MeshMemberTable>{ range.m_offset, range.m_size };
        }

        [[nodiscard]] bool TryReallocateRows(DB::Slice<MeshMemberTable>& rows, const uint32_t rowCount)
        {
            RowRangeHandle range{ rows.m_rowIndex, rows.m_count };
            if (!TryReallocateRowsUninitialized(range, rowCount))
                return false;

            for (uint32_t rowIndex = rows.m_count; rowIndex < rowCount; ++rowIndex)
            {
                const RWRow row = WriteRow(rowIndex + range.m_offset);
                row.m_instance.Construct();
            }

            rows = { range.m_offset, range.m_size };
            return true;
        }

        void Free(const DB::Ref<MeshMemberTable> row)
        {
            TableBase::Free(row.m_rowIndex);
        }

        void Free(const DB::Slice<MeshMemberTable> rows)
        {
            TableBase::Free(RowRangeHandle{ rows.m_rowIndex, rows.m_count });
        }

        [[nodiscard]] Row ReadRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            const DB::StoragePage* page = m_pages[pageIndex];
            const std::byte* storage = page->GetHostStorage();

            Row row;
            row.m_instance.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] Row ReadRow(const DB::Ref<MeshMemberTable> reference)
        {
            return ReadRow(reference.m_rowIndex);
        }

        [[nodiscard]] RWRow WriteRow(const uint32_t rowIndex)
        {
            const uint32_t pageIndex = rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = rowIndex % kRowsPerPage;

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();

            RWRow row;
            row.m_instance.Setup(storage, localRowIndex);
            return row;
        }

        [[nodiscard]] RWRow WriteRow(const DB::Ref<MeshMemberTable> reference)
        {
            return WriteRow(reference.m_rowIndex);
        }

        void CopyColumn(const DB::Slice<MeshMemberTable> destination, const festd::span<const DB::Ref<MeshInstanceTable>> source)
        {
            FE_Assert(destination.m_count == source.size());

            if (destination.m_count == 0)
                return;

            const uint32_t pageIndex = destination.m_rowIndex / kRowsPerPage;
            const uint32_t localRowIndex = destination.m_rowIndex % kRowsPerPage;
            FE_Assert(destination.m_count <= kRowsPerPage - localRowIndex, "The whole range must fit in a single page");

            DB::StoragePage* page = m_pages[pageIndex];
            m_database->MarkPageDirty(page);
            std::byte* storage = page->GetHostStorage();
            auto* destinationData = reinterpret_cast<DB::Ref<MeshInstanceTable>*>(storage + kOffset_m_instance) + localRowIndex;
            festd::copy(source, destinationData);
        }
    };
} // namespace FE::Graphics
