file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "*.cpp" "*.h")
list(REMOVE_ITEM SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/EntityAssetIntegration.cpp")
add_executable(FeFrameworkTests ${SOURCES})
fe_configure_target(FeFrameworkTests)
target_include_directories(FeFrameworkTests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(FeFrameworkTests PRIVATE FeFramework gtest gmock)
set_target_properties(FeFrameworkTests PROPERTIES FOLDER "Modules/Framework")
include(GoogleTest)
gtest_discover_tests(FeFrameworkTests)

target_compile_definitions(FeFrameworkTests PRIVATE FE_FRAMEWORK_CORE_FIXTURES="${PROJECT_SOURCE_DIR}/FerrumCore/Tests/Fixtures/Artifacts")

add_executable(FeFrameworkAssetTests Main.cpp EntityAssetIntegration.cpp Reflection.gen.cpp)
fe_configure_target(FeFrameworkAssetTests)
target_include_directories(FeFrameworkAssetTests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(FeFrameworkAssetTests PRIVATE FeFramework AssetBuilder gtest gmock)
set_target_properties(FeFrameworkAssetTests PROPERTIES FOLDER "Modules/Framework")
target_compile_definitions(FeFrameworkAssetTests PRIVATE FE_ENTITY_ASSET_TEST_OUTPUT="${PROJECT_BINARY_DIR}/EntityAssetTests")
gtest_discover_tests(FeFrameworkAssetTests)
