//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#include <Core/RTTI/ReflectionContext.h>

#include <EntityTestTypes.h>


namespace FE
{
    void CallLinkerAnchor_FrameworkTests() {}
} // namespace FE


namespace FE::Framework::Tests
{
    const Rtti::TypeID Number::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x01,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6001()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Number::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6001();
    }

    void Number::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6001();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x01, // FE::Framework::Tests::Number
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x17, 0x41, 0x96, 0xbd, 0x8b, 0xfe, 0x40, 0x49, 0xb7, 0x2e, 0x8a, 0x07, 0xad, 0x37, 0x26, 0x59, // int32_t m_value
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_value = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_value",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &Number::m_value,
                                                        kAttributes_m_value,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Number>(typeInstance,
                                     Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                     "FE::Framework::Tests::Number",
                                     kBaseClassTypeIDs,
                                     kAttributes,
                                     kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6001(&Number::Reflect);

    FE::Serialization::ResultCode Number::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_value", m_value);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode Number::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_value", m_value);
        }

        return context.GetResultCode();
    }

    uint64_t Number::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x01,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_value", 7);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_value)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t Number::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID Extra::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x02,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6002()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Extra::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6002();
    }

    void Extra::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6002();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x02, // FE::Framework::Tests::Extra
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x17, 0x41, 0x96, 0xbd, 0x8b, 0xfe, 0x40, 0x49, 0xb7, 0x2e, 0x8a, 0x07, 0xad, 0x37, 0x26, 0x59, // int32_t m_value
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_value = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_value",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &Extra::m_value,
                                                        kAttributes_m_value,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Extra>(typeInstance,
                                    Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                    "FE::Framework::Tests::Extra",
                                    kBaseClassTypeIDs,
                                    kAttributes,
                                    kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6002(&Extra::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID MoveOnly::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x03,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6003()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MoveOnly::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6003();
    }

    void MoveOnly::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6003();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x03, // FE::Framework::Tests::MoveOnly
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x17, 0x41, 0x96, 0xbd, 0x8b, 0xfe, 0x40, 0x49, 0xb7, 0x2e, 0x8a, 0x07, 0xad, 0x37, 0x26, 0x59, // int32_t m_value
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_value = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_value",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &MoveOnly::m_value,
                                                        kAttributes_m_value,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<MoveOnly>(typeInstance,
                                       Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                       "FE::Framework::Tests::MoveOnly",
                                       kBaseClassTypeIDs,
                                       kAttributes,
                                       kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6003(&MoveOnly::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID Aligned::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x04,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6004()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Aligned::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6004();
    }

    void Aligned::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6004();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x04, // FE::Framework::Tests::Aligned
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x76, 0xe0, 0xd6, 0x16, 0xa6, 0x46, 0x42, 0x2a, 0xb5, 0x06, 0x07, 0xad, 0xbe, 0x41, 0x75, 0x6b, // uint64_t m_value
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_value = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_value",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &Aligned::m_value,
                                                        kAttributes_m_value,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Aligned>(typeInstance,
                                      Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                      "FE::Framework::Tests::Aligned",
                                      kBaseClassTypeIDs,
                                      kAttributes,
                                      kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6004(&Aligned::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID Huge::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x05,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6005()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Huge::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6005();
    }

    void Huge::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6005();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x05, // FE::Framework::Tests::Huge
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x80, 0xe0, 0x74, 0xd8, 0xc4, 0xc0, 0x41, 0x90, 0xb7, 0x16, 0x70, 0x1d, 0xba, 0x47, 0xf9, 0xf7, // uint8_t m_data
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_data = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<70000>("m_data",
                                                            Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                            &Huge::m_data,
                                                            kAttributes_m_data,
                                                            Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Huge>(typeInstance,
                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                   "FE::Framework::Tests::Huge",
                                   kBaseClassTypeIDs,
                                   kAttributes,
                                   kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6005(&Huge::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID Hook::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x07,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6007()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Hook::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6007();
    }

    void Hook::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6007();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x07, // FE::Framework::Tests::Hook
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x17, 0x41, 0x96, 0xbd, 0x8b, 0xfe, 0x40, 0x49, 0xb7, 0x2e, 0x8a, 0x07, 0xad, 0x37, 0x26, 0x59, // int32_t m_label
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_label = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_label",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &Hook::m_label,
                                                        kAttributes_m_label,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<Hook>(typeInstance,
                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                   "FE::Framework::Tests::Hook",
                                   kBaseClassTypeIDs,
                                   kAttributes,
                                   kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6007(&Hook::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID AssetComponent::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x08,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6008()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& AssetComponent::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6008();
    }

    void AssetComponent::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6008();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x08, // FE::Framework::Tests::AssetComponent
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_hard
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_soft
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_hard = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_soft = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_hard",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &AssetComponent::m_hard,
                                                        kAttributes_m_hard,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_soft",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &AssetComponent::m_soft,
                                                        kAttributes_m_soft,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<AssetComponent>(typeInstance,
                                             Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                             "FE::Framework::Tests::AssetComponent",
                                             kBaseClassTypeIDs,
                                             kAttributes,
                                             kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6008(&AssetComponent::Reflect);

    FE::Serialization::ResultCode AssetComponent::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_hard", m_hard);
            object.Field("m_soft", m_soft);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode AssetComponent::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_hard", m_hard);
            object.Field("m_soft", m_soft);
        }

        return context.GetResultCode();
    }

    uint64_t AssetComponent::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x08,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_hard", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_hard)>());
            hasher.Update("m_soft", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_soft)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t AssetComponent::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID CustomLoad::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x09,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6009()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& CustomLoad::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6009();
    }

    void CustomLoad::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6009();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x09, // FE::Framework::Tests::CustomLoad
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[1 * sizeof(Rtti::TypeID)] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_asset
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_asset = {};

        static const festd::array<Rtti::FieldInfo, 1> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_asset",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &CustomLoad::m_asset,
                                                        kAttributes_m_asset,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<CustomLoad>(typeInstance,
                                         Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                         "FE::Framework::Tests::CustomLoad",
                                         kBaseClassTypeIDs,
                                         kAttributes,
                                         kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6009(&CustomLoad::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID ReferenceComponent::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x15,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6015()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ReferenceComponent::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6015();
    }

    void ReferenceComponent::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6015();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x15, // FE::Framework::Tests::ReferenceComponent
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0xb9, 0xdb, 0xe8, 0x0d, 0x6a, 0xb0, 0x48, 0x6a,
            0xab, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, // FE::Framework::EntityReference m_internal
            0xb9, 0xdb, 0xe8, 0x0d, 0x6a, 0xb0, 0x48, 0x6a,
            0xab, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, // FE::Framework::EntityReference m_external
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_internal = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_external = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_internal",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &ReferenceComponent::m_internal,
                                                        kAttributes_m_internal,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_external",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &ReferenceComponent::m_external,
                                                        kAttributes_m_external,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<ReferenceComponent>(typeInstance,
                                                 Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                 "FE::Framework::Tests::ReferenceComponent",
                                                 kBaseClassTypeIDs,
                                                 kAttributes,
                                                 kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6015(&ReferenceComponent::Reflect);

    FE::Serialization::ResultCode ReferenceComponent::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_internal", m_internal);
            object.Field("m_external", m_external);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode ReferenceComponent::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_internal", m_internal);
            object.Field("m_external", m_external);
        }

        return context.GetResultCode();
    }

    uint64_t ReferenceComponent::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x15,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_internal", 10);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_internal)>());
            hasher.Update("m_external", 10);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_external)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t ReferenceComponent::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID CollectionAssets::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x16,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6016()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& CollectionAssets::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6016();
    }

    void CollectionAssets::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6016();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x16, // FE::Framework::Tests::CollectionAssets
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(Rtti::TypeID)] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_hard
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // <unknown> m_soft
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_hard = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_soft = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_hard",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &CollectionAssets::m_hard,
                                                        kAttributes_m_hard,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_soft",
                                                        Rtti::TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &CollectionAssets::m_soft,
                                                        kAttributes_m_soft,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<CollectionAssets>(typeInstance,
                                               Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                               "FE::Framework::Tests::CollectionAssets",
                                               kBaseClassTypeIDs,
                                               kAttributes,
                                               kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6016(&CollectionAssets::Reflect);

    FE::Serialization::ResultCode CollectionAssets::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_hard", m_hard);
            object.Field("m_soft", m_soft);
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode CollectionAssets::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
            object.Field("m_hard", m_hard);
            object.Field("m_soft", m_soft);
        }

        return context.GetResultCode();
    }

    uint64_t CollectionAssets::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x16,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update("m_hard", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_hard)>());
            hasher.Update("m_soft", 6);
            hasher.UpdateRaw(FE::Serialization::GetSchemaHash<decltype(m_soft)>());
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t CollectionAssets::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID SpawnFromLoad::TypeID = Rtti::TypeID{
        0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x17,
    };

    namespace
    {
        Rtti::Type& RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6017()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SpawnFromLoad::RTTI_GetType()
    {
        return RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6017();
    }

    void SpawnFromLoad::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1c7ec0da7e5b4ef297ef8a0b846c6017();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2,
            0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x17, // FE::Framework::Tests::SpawnFromLoad
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SpawnFromLoad>(typeInstance,
                                            Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                            "FE::Framework::Tests::SpawnFromLoad",
                                            kBaseClassTypeIDs,
                                            kAttributes,
                                            kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1c7ec0da7e5b4ef297ef8a0b846c6017(&SpawnFromLoad::Reflect);

    FE::Serialization::ResultCode SpawnFromLoad::Serialize(FE::Serialization::SerializationContext& context) const
    {
        if (auto object = context.BeginObject())
        {
        }

        return context.GetResultCode();
    }

    FE::Serialization::ResultCode SpawnFromLoad::Deserialize(FE::Serialization::DeserializationContext& context)
    {
        if (auto object = context.BeginObject())
        {
        }

        return context.GetResultCode();
    }

    uint64_t SpawnFromLoad::RTTI_GetSerializationSchemaHash()
    {
        static const uint64_t kHash = [] {
            static constexpr uint8_t kTypeIDBytes[] = {
                0x1c, 0x7e, 0xc0, 0xda, 0x7e, 0x5b, 0x4e, 0xf2, 0x97, 0xef, 0x8a, 0x0b, 0x84, 0x6c, 0x60, 0x17,
            };
            FE::Hasher hasher;
            hasher.Update(kTypeIDBytes, sizeof(kTypeIDBytes));
            hasher.Update(0);
            return hasher.Finalize();
        }();

        return kHash;
    }

    uint32_t SpawnFromLoad::RTTI_GetSerializationVersion()
    {
        return 0;
    }

} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID SnapshotSystem::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf0,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f0(SnapshotSystem* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf0, // FE::Framework::Tests::SnapshotSystem (this type)
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::WorldSystem*>(thisPtr);

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f0()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SnapshotSystem::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f0();
    }

    void* FE_VECTORCALL SnapshotSystem::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f0(this, typeID);
    }

    const void* FE_VECTORCALL SnapshotSystem::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f0(const_cast<SnapshotSystem*>(this), typeID);
    }
    void SnapshotSystem::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f0();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf0, // FE::Framework::Tests::SnapshotSystem
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SnapshotSystem>(typeInstance,
                                             Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                             "FE::Framework::Tests::SnapshotSystem",
                                             kBaseClassTypeIDs,
                                             kAttributes,
                                             kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<SnapshotSystem*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f0(&SnapshotSystem::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID SystemPrefix::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f1(SystemPrefix* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[1 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix (this type)
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f1()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SystemPrefix::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f1();
    }

    void* FE_VECTORCALL SystemPrefix::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f1(this, typeID);
    }

    const void* FE_VECTORCALL SystemPrefix::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f1(const_cast<SystemPrefix*>(this), typeID);
    }
    void SystemPrefix::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f1();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix
        };

        static constexpr alignas(16) festd::array<uint8_t, 0 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {};
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SystemPrefix>(typeInstance,
                                           Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                           "FE::Framework::Tests::SystemPrefix",
                                           kBaseClassTypeIDs,
                                           kAttributes,
                                           kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<SystemPrefix*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f1(&SystemPrefix::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID OffsetSnapshotSystem::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf2,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f2(OffsetSnapshotSystem* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[4 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf2, // FE::Framework::Tests::OffsetSnapshotSystem (this type)
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf0, // FE::Framework::Tests::SnapshotSystem
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::Tests::SystemPrefix*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::Tests::SnapshotSystem*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 3 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::WorldSystem*>(thisPtr);

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f2()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& OffsetSnapshotSystem::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f2();
    }

    void* FE_VECTORCALL OffsetSnapshotSystem::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f2(this, typeID);
    }

    const void* FE_VECTORCALL OffsetSnapshotSystem::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f2(const_cast<OffsetSnapshotSystem*>(this), typeID);
    }
    void OffsetSnapshotSystem::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f2();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf2, // FE::Framework::Tests::OffsetSnapshotSystem
        };

        static constexpr alignas(16) festd::array<uint8_t, 3 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf0, // FE::Framework::Tests::SnapshotSystem
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<OffsetSnapshotSystem>(typeInstance,
                                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                   "FE::Framework::Tests::OffsetSnapshotSystem",
                                                   kBaseClassTypeIDs,
                                                   kAttributes,
                                                   kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<OffsetSnapshotSystem*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f2(&OffsetSnapshotSystem::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID NonDefaultSystem::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf3,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f3(NonDefaultSystem* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf3, // FE::Framework::Tests::NonDefaultSystem (this type)
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::WorldSystem*>(thisPtr);

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f3()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& NonDefaultSystem::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f3();
    }

    void* FE_VECTORCALL NonDefaultSystem::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f3(this, typeID);
    }

    const void* FE_VECTORCALL NonDefaultSystem::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f3(const_cast<NonDefaultSystem*>(this), typeID);
    }
    void NonDefaultSystem::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f3();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf3, // FE::Framework::Tests::NonDefaultSystem
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfe, // FE::Framework::WorldSystem
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<NonDefaultSystem>(typeInstance,
                                               Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                               "FE::Framework::Tests::NonDefaultSystem",
                                               kBaseClassTypeIDs,
                                               kAttributes,
                                               kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<NonDefaultSystem*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f3(&NonDefaultSystem::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID SnapshotService::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf4,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f4(SnapshotService* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf4, // FE::Framework::Tests::SnapshotService (this type)
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfd, // FE::Framework::WorldService
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::WorldService*>(thisPtr);

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f4()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SnapshotService::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f4();
    }

    void* FE_VECTORCALL SnapshotService::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f4(this, typeID);
    }

    const void* FE_VECTORCALL SnapshotService::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f4(const_cast<SnapshotService*>(this), typeID);
    }
    void SnapshotService::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f4();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf4, // FE::Framework::Tests::SnapshotService
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfd, // FE::Framework::WorldService
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SnapshotService>(typeInstance,
                                              Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                              "FE::Framework::Tests::SnapshotService",
                                              kBaseClassTypeIDs,
                                              kAttributes,
                                              kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<SnapshotService*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f4(&SnapshotService::Reflect);
} // namespace FE::Framework::Tests


namespace FE::Framework::Tests
{
    const Rtti::TypeID OffsetSnapshotService::TypeID = Rtti::TypeID{
        0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55, 0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf5,
    };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f5(OffsetSnapshotService* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[4 * sizeof(Rtti::TypeID)] = {
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf5, // FE::Framework::Tests::OffsetSnapshotService (this type)
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf4, // FE::Framework::Tests::SnapshotService
                0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
                0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfd, // FE::Framework::WorldService
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::Tests::SystemPrefix*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::Tests::SnapshotService*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 3 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Framework::WorldService*>(thisPtr);

            return nullptr;
        }
        Rtti::Type& RTTI_GetMutableType_aaa6912644274055b1c404013aae09f5()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& OffsetSnapshotService::RTTI_GetType()
    {
        return RTTI_GetMutableType_aaa6912644274055b1c404013aae09f5();
    }

    void* FE_VECTORCALL OffsetSnapshotService::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f5(this, typeID);
    }

    const void* FE_VECTORCALL OffsetSnapshotService::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_aaa6912644274055b1c404013aae09f5(const_cast<OffsetSnapshotService*>(this), typeID);
    }
    void OffsetSnapshotService::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_aaa6912644274055b1c404013aae09f5();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf5, // FE::Framework::Tests::OffsetSnapshotService
        };

        static constexpr alignas(16) festd::array<uint8_t, 3 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf1, // FE::Framework::Tests::SystemPrefix
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xf4, // FE::Framework::Tests::SnapshotService
            0xaa, 0xa6, 0x91, 0x26, 0x44, 0x27, 0x40, 0x55,
            0xb1, 0xc4, 0x04, 0x01, 0x3a, 0xae, 0x09, 0xfd, // FE::Framework::WorldService
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<OffsetSnapshotService>(typeInstance,
                                                    Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                    "FE::Framework::Tests::OffsetSnapshotService",
                                                    kBaseClassTypeIDs,
                                                    kAttributes,
                                                    kFields);
        typeInstance.m_cast = [](void* instance, Rtti::TypeID target) {
            return static_cast<OffsetSnapshotService*>(instance)->RTTI_TryCast(target);
        };
    }

    static Rtti::TypeRegistrar GTypeRegistrar_aaa6912644274055b1c404013aae09f5(&OffsetSnapshotService::Reflect);
} // namespace FE::Framework::Tests
