//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#include <Graphics/Assets/IModelAssetManager.h>
#include <Graphics/Assets/ITextureAssetManager.h>
#include <Graphics/Assets/ModelAssetManager.h>
#include <Graphics/Assets/TextureAssetManager.h>
#include <Graphics/Database/Database.h>
#include <Graphics/Features/Mesh/MeshSceneModule.h>
#include <Graphics/Renderer.h>
#include <Graphics/RendererImpl.h>
#include <Graphics/Scene/Scene.h>
#include <Graphics/Scene/SceneImpl.h>
#include <Graphics/Scene/View.h>
#include <Graphics/Scene/ViewImpl.h>
#include <Graphics/Tables/MeshGroupTable.h>
#include <Graphics/Tables/MeshInstanceTable.h>
#include <Graphics/Tables/MeshLodInfoTable.h>
#include <Shaders/Passes/Tools/Blit/Blit.h>
#include <Shaders/Passes/Tools/Downsample/Downsample.h>


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID MeshGroupTable::TypeID = Rtti::TypeID{ "03321e1e-0a92-5203-b75c-027838609287" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_03321e1e0a925203b75c027838609287(MeshGroupTable* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x03, 0x32, 0x1e, 0x1e, 0x0a, 0x92, 0x52, 0x03,
                0xb7, 0x5c, 0x02, 0x78, 0x38, 0x60, 0x92, 0x87, // FE::Graphics::MeshGroupTable (this type)
                0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
                0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::DB::TableBase*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_03321e1e0a925203b75c027838609287()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MeshGroupTable::RTTI_GetType()
    {
        return RTTI_GetMutableType_03321e1e0a925203b75c027838609287();
    }

    void* FE_VECTORCALL MeshGroupTable::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_03321e1e0a925203b75c027838609287(this, typeID);
    }

    const void* FE_VECTORCALL MeshGroupTable::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_03321e1e0a925203b75c027838609287(const_cast<MeshGroupTable*>(this), typeID);
    }

    void MeshGroupTable::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_03321e1e0a925203b75c027838609287();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x03, 0x32, 0x1e, 0x1e, 0x0a, 0x92, 0x52, 0x03,
            0xb7, 0x5c, 0x02, 0x78, 0x38, 0x60, 0x92, 0x87, // FE::Graphics::MeshGroupTable
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
            0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<MeshGroupTable>(typeInstance,
                                             Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                             "FE::Graphics::MeshGroupTable",
                                             kBaseClassTypeIDs,
                                             kAttributes,
                                             kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_03321e1e0a925203b75c027838609287(&MeshGroupTable::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID ViewImpl::TypeID = Rtti::TypeID{ "113ac827-90ac-48f7-9a7a-4c7ae0695ad8" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_113ac82790ac48f79a7a4c7ae0695ad8(ViewImpl* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x11, 0x3a, 0xc8, 0x27, 0x90, 0xac, 0x48, 0xf7,
                0x9a, 0x7a, 0x4c, 0x7a, 0xe0, 0x69, 0x5a, 0xd8, // FE::Graphics::ViewImpl (this type)
                0x4b, 0x83, 0xaf, 0xa4, 0x70, 0xb9, 0x4a, 0xf9,
                0x8a, 0xb8, 0x10, 0x82, 0xc6, 0xb4, 0x98, 0x49, // FE::Graphics::View
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::View*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_113ac82790ac48f79a7a4c7ae0695ad8()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ViewImpl::RTTI_GetType()
    {
        return RTTI_GetMutableType_113ac82790ac48f79a7a4c7ae0695ad8();
    }

    void* FE_VECTORCALL ViewImpl::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_113ac82790ac48f79a7a4c7ae0695ad8(this, typeID);
    }

    const void* FE_VECTORCALL ViewImpl::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_113ac82790ac48f79a7a4c7ae0695ad8(const_cast<ViewImpl*>(this), typeID);
    }

    void ViewImpl::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_113ac82790ac48f79a7a4c7ae0695ad8();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x11, 0x3a, 0xc8, 0x27, 0x90, 0xac, 0x48, 0xf7,
            0x9a, 0x7a, 0x4c, 0x7a, 0xe0, 0x69, 0x5a, 0xd8, // FE::Graphics::ViewImpl
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x4b, 0x83, 0xaf, 0xa4, 0x70, 0xb9, 0x4a, 0xf9,
            0x8a, 0xb8, 0x10, 0x82, 0xc6, 0xb4, 0x98, 0x49, // FE::Graphics::View
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<ViewImpl>(typeInstance,
                                       Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                       "FE::Graphics::ViewImpl",
                                       kBaseClassTypeIDs,
                                       kAttributes,
                                       kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_113ac82790ac48f79a7a4c7ae0695ad8(&ViewImpl::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID MeshSceneModule::TypeID = Rtti::TypeID{ "1784843c-5085-4289-aa82-04c480e423ee" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_1784843c50854289aa8204c480e423ee(MeshSceneModule* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x17, 0x84, 0x84, 0x3c, 0x50, 0x85, 0x42, 0x89,
                0xaa, 0x82, 0x04, 0xc4, 0x80, 0xe4, 0x23, 0xee, // FE::Graphics::MeshSceneModule (this type)
                0x77, 0x29, 0xe6, 0x83, 0x86, 0x38, 0x47, 0x12,
                0x81, 0xd3, 0xb1, 0xc7, 0x8b, 0x16, 0xbf, 0xe3, // FE::Graphics::SceneModuleBase
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::SceneModuleBase*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_1784843c50854289aa8204c480e423ee()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MeshSceneModule::RTTI_GetType()
    {
        return RTTI_GetMutableType_1784843c50854289aa8204c480e423ee();
    }

    void* FE_VECTORCALL MeshSceneModule::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_1784843c50854289aa8204c480e423ee(this, typeID);
    }

    const void* FE_VECTORCALL MeshSceneModule::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_1784843c50854289aa8204c480e423ee(const_cast<MeshSceneModule*>(this), typeID);
    }

    void MeshSceneModule::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_1784843c50854289aa8204c480e423ee();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x17, 0x84, 0x84, 0x3c, 0x50, 0x85, 0x42, 0x89,
            0xaa, 0x82, 0x04, 0xc4, 0x80, 0xe4, 0x23, 0xee, // FE::Graphics::MeshSceneModule
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x77, 0x29, 0xe6, 0x83, 0x86, 0x38, 0x47, 0x12,
            0x81, 0xd3, 0xb1, 0xc7, 0x8b, 0x16, 0xbf, 0xe3, // FE::Graphics::SceneModuleBase
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<MeshSceneModule>(typeInstance,
                                              Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                              "FE::Graphics::MeshSceneModule",
                                              kBaseClassTypeIDs,
                                              kAttributes,
                                              kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_1784843c50854289aa8204c480e423ee(&MeshSceneModule::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Rtti
{
    namespace
    {
        Type& GetMutableType_1f7c86ca9dfb5709a3e6fcf114c571e6()
        {
            static Type typeInstance;
            return typeInstance;
        }
    } // namespace

    template<>
    const Type& GetType<FE::Graphics::Tools::Downsample::Constants>()
    {
        return GetMutableType_1f7c86ca9dfb5709a3e6fcf114c571e6();
    }

    template<>
    TypeID GetTypeID<FE::Graphics::Tools::Downsample::Constants>()
    {
        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x1f, 0x7c, 0x86, 0xca, 0x9d, 0xfb, 0x57, 0x09,
            0xa3, 0xe6, 0xfc, 0xf1, 0x14, 0xc5, 0x71, 0xe6, // FE::Graphics::Tools::Downsample::Constants
        };

        return TypeID::LoadAligned(kTypeIDBytes);
    }

    void Internal::ExternalTypeReflector<FE::Graphics::Tools::Downsample::Constants>::Reflect(ReflectionContext& context)
    {
        Type& typeInstance = GetMutableType_1f7c86ca9dfb5709a3e6fcf114c571e6();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x1f, 0x7c, 0x86, 0xca, 0x9d, 0xfb, 0x57, 0x09,
            0xa3, 0xe6, 0xfc, 0xf1, 0x14, 0xc5, 0x71, 0xe6, // FE::Graphics::Tools::Downsample::Constants
        };

        static constexpr alignas(16) uint8_t kFieldTypeIDs[10 * sizeof(TypeID)] = {
            0x33, 0x4f, 0x07, 0x50, 0x1b, 0x4e, 0x4f, 0x4c,
            0xac, 0x6f, 0x98, 0x53, 0x82, 0xd4, 0xbd, 0x11, // uint32_t m_mips
            0x33, 0x4f, 0x07, 0x50, 0x1b, 0x4e, 0x4f, 0x4c,
            0xac, 0x6f, 0x98, 0x53, 0x82, 0xd4, 0xbd, 0x11, // uint32_t m_numWorkGroups
            0x9b, 0x89, 0x43, 0xc5, 0x64, 0x3c, 0x4f, 0x9b,
            0x9f, 0x20, 0xf2, 0xa2, 0x82, 0x35, 0x5a, 0xd2, // FE::Vector2Base<unsigned int> m_workGroupOffset
            0x25, 0xc9, 0x34, 0xe8, 0xed, 0x78, 0x41, 0xd5,
            0xb3, 0xe2, 0xe1, 0x3b, 0x97, 0xaf, 0xca, 0xc6, // FE::Vector2Base<float> m_invInputSize
            0x4b, 0x51, 0x72, 0xef, 0x1e, 0x7a, 0x43, 0xe2,
            0xb5, 0x89, 0x1b, 0xac, 0x65, 0x42, 0x8e, 0x92, // FE::Graphics::TextureSRVDescriptor m_input
            0xb0, 0x30, 0x04, 0xc4, 0x31, 0x08, 0x46, 0xb1,
            0xa4, 0x75, 0x63, 0x1c, 0xdc, 0x59, 0xbe, 0xdd, // FE::Graphics::BufferUAVDescriptor m_internalGlobalAtomic
            0x39, 0x28, 0x7d, 0x51, 0xe5, 0x73, 0x44, 0x28,
            0xaa, 0xdf, 0x74, 0x82, 0x7c, 0xd4, 0x35, 0x1e, // FE::Graphics::TextureUAVDescriptor m_inputSrcMidMip
            0x39, 0x28, 0x7d, 0x51, 0xe5, 0x73, 0x44, 0x28,
            0xaa, 0xdf, 0x74, 0x82, 0x7c, 0xd4, 0x35, 0x1e, // FE::Graphics::TextureUAVDescriptor m_inputSrcMips
            0x0a, 0xdc, 0x65, 0xde, 0x1b, 0xa6, 0x4a, 0x60,
            0xb3, 0x20, 0x33, 0x3a, 0xd0, 0xc2, 0xf2, 0x7b, // FE::Graphics::SamplerDescriptor m_linearClamp
            0x66, 0xd8, 0x93, 0x0b, 0x34, 0x58, 0x48, 0x47,
            0xb6, 0xf1, 0x00, 0x2c, 0x70, 0xdc, 0x1e, 0xd2, // float m_padding
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_mips = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_numWorkGroups = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_workGroupOffset = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_invInputSize = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_input = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_internalGlobalAtomic = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_inputSrcMidMip = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_inputSrcMips = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_linearClamp = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_padding = {};

        static const festd::array<Rtti::FieldInfo, 10> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_mips",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_mips,
                                                        kAttributes_m_mips,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_numWorkGroups",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_numWorkGroups,
                                                        kAttributes_m_numWorkGroups,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_workGroupOffset",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_workGroupOffset,
                                                        kAttributes_m_workGroupOffset,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_invInputSize",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 3 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_invInputSize,
                                                        kAttributes_m_invInputSize,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_input",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 4 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_input,
                                                        kAttributes_m_input,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_internalGlobalAtomic",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 5 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_internalGlobalAtomic,
                                                        kAttributes_m_internalGlobalAtomic,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_inputSrcMidMip",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 6 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_inputSrcMidMip,
                                                        kAttributes_m_inputSrcMidMip,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<13>("m_inputSrcMips",
                                                         TypeID::LoadAligned(kFieldTypeIDs + 7 * sizeof(TypeID)),
                                                         &FE::Graphics::Tools::Downsample::Constants::m_inputSrcMips,
                                                         kAttributes_m_inputSrcMips,
                                                         Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_linearClamp",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 8 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_linearClamp,
                                                        kAttributes_m_linearClamp,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_padding",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 9 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::Constants::m_padding,
                                                        kAttributes_m_padding,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<FE::Graphics::Tools::Downsample::Constants>(typeInstance,
                                                                         Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                                         "FE::Graphics::Tools::Downsample::Constants",
                                                                         {},
                                                                         kAttributes,
                                                                         kFields);
    }

    static TypeRegistrar GTypeRegistrar_1f7c86ca9dfb5709a3e6fcf114c571e6(
        &Internal::ExternalTypeReflector<FE::Graphics::Tools::Downsample::Constants>::Reflect);
} // namespace FE::Rtti


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID Scene::TypeID = Rtti::TypeID{ "20121f05-8d10-4427-9925-2dba388379c9" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_20121f058d10442799252dba388379c9(Scene* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x20, 0x12, 0x1f, 0x05, 0x8d, 0x10, 0x44, 0x27,
                0x99, 0x25, 0x2d, 0xba, 0x38, 0x83, 0x79, 0xc9, // FE::Graphics::Scene (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_20121f058d10442799252dba388379c9()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Scene::RTTI_GetType()
    {
        return RTTI_GetMutableType_20121f058d10442799252dba388379c9();
    }

    void* FE_VECTORCALL Scene::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_20121f058d10442799252dba388379c9(this, typeID);
    }

    const void* FE_VECTORCALL Scene::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_20121f058d10442799252dba388379c9(const_cast<Scene*>(this), typeID);
    }

    void Scene::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_20121f058d10442799252dba388379c9();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x20, 0x12, 0x1f, 0x05, 0x8d, 0x10, 0x44, 0x27, 0x99, 0x25, 0x2d, 0xba, 0x38, 0x83, 0x79, 0xc9, // FE::Graphics::Scene
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<Scene>(typeInstance,
                                    Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                    "FE::Graphics::Scene",
                                    kBaseClassTypeIDs,
                                    kAttributes,
                                    kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_20121f058d10442799252dba388379c9(&Scene::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID RendererModuleBase::TypeID = Rtti::TypeID{ "273b0f50-b991-4323-a516-6c87bbcd83a1" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_273b0f50b9914323a5166c87bbcd83a1(RendererModuleBase* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x27, 0x3b, 0x0f, 0x50, 0xb9, 0x91, 0x43, 0x23,
                0xa5, 0x16, 0x6c, 0x87, 0xbb, 0xcd, 0x83, 0xa1, // FE::Graphics::RendererModuleBase (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_273b0f50b9914323a5166c87bbcd83a1()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& RendererModuleBase::RTTI_GetType()
    {
        return RTTI_GetMutableType_273b0f50b9914323a5166c87bbcd83a1();
    }

    void* FE_VECTORCALL RendererModuleBase::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_273b0f50b9914323a5166c87bbcd83a1(this, typeID);
    }

    const void* FE_VECTORCALL RendererModuleBase::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_273b0f50b9914323a5166c87bbcd83a1(const_cast<RendererModuleBase*>(this), typeID);
    }

    void RendererModuleBase::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_273b0f50b9914323a5166c87bbcd83a1();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x27, 0x3b, 0x0f, 0x50, 0xb9, 0x91, 0x43, 0x23,
            0xa5, 0x16, 0x6c, 0x87, 0xbb, 0xcd, 0x83, 0xa1, // FE::Graphics::RendererModuleBase
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<RendererModuleBase>(typeInstance,
                                                 Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                 "FE::Graphics::RendererModuleBase",
                                                 kBaseClassTypeIDs,
                                                 kAttributes,
                                                 kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_273b0f50b9914323a5166c87bbcd83a1(&RendererModuleBase::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID MeshLodInfoTable::TypeID = Rtti::TypeID{ "429a06b5-0beb-5171-87f8-18737671fb7f" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_429a06b50beb517187f818737671fb7f(MeshLodInfoTable* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x42, 0x9a, 0x06, 0xb5, 0x0b, 0xeb, 0x51, 0x71,
                0x87, 0xf8, 0x18, 0x73, 0x76, 0x71, 0xfb, 0x7f, // FE::Graphics::MeshLodInfoTable (this type)
                0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
                0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::DB::TableBase*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_429a06b50beb517187f818737671fb7f()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MeshLodInfoTable::RTTI_GetType()
    {
        return RTTI_GetMutableType_429a06b50beb517187f818737671fb7f();
    }

    void* FE_VECTORCALL MeshLodInfoTable::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_429a06b50beb517187f818737671fb7f(this, typeID);
    }

    const void* FE_VECTORCALL MeshLodInfoTable::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_429a06b50beb517187f818737671fb7f(const_cast<MeshLodInfoTable*>(this), typeID);
    }

    void MeshLodInfoTable::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_429a06b50beb517187f818737671fb7f();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x42, 0x9a, 0x06, 0xb5, 0x0b, 0xeb, 0x51, 0x71,
            0x87, 0xf8, 0x18, 0x73, 0x76, 0x71, 0xfb, 0x7f, // FE::Graphics::MeshLodInfoTable
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
            0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<MeshLodInfoTable>(typeInstance,
                                               Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                               "FE::Graphics::MeshLodInfoTable",
                                               kBaseClassTypeIDs,
                                               kAttributes,
                                               kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_429a06b50beb517187f818737671fb7f(&MeshLodInfoTable::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID View::TypeID = Rtti::TypeID{ "4b83afa4-70b9-4af9-8ab8-1082c6b49849" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_4b83afa470b94af98ab81082c6b49849(View* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x4b, 0x83, 0xaf, 0xa4, 0x70, 0xb9, 0x4a, 0xf9,
                0x8a, 0xb8, 0x10, 0x82, 0xc6, 0xb4, 0x98, 0x49, // FE::Graphics::View (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_4b83afa470b94af98ab81082c6b49849()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& View::RTTI_GetType()
    {
        return RTTI_GetMutableType_4b83afa470b94af98ab81082c6b49849();
    }

    void* FE_VECTORCALL View::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_4b83afa470b94af98ab81082c6b49849(this, typeID);
    }

    const void* FE_VECTORCALL View::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_4b83afa470b94af98ab81082c6b49849(const_cast<View*>(this), typeID);
    }

    void View::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_4b83afa470b94af98ab81082c6b49849();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x4b, 0x83, 0xaf, 0xa4, 0x70, 0xb9, 0x4a, 0xf9, 0x8a, 0xb8, 0x10, 0x82, 0xc6, 0xb4, 0x98, 0x49, // FE::Graphics::View
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<View>(typeInstance,
                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                   "FE::Graphics::View",
                                   kBaseClassTypeIDs,
                                   kAttributes,
                                   kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_4b83afa470b94af98ab81082c6b49849(&View::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID ModelAssetManager::TypeID = Rtti::TypeID{ "6ca86f05-71ea-45d8-9d22-d57e469f4752" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_6ca86f0571ea45d89d22d57e469f4752(ModelAssetManager* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[4 * sizeof(Rtti::TypeID)] = {
                0x6c, 0xa8, 0x6f, 0x05, 0x71, 0xea, 0x45, 0xd8,
                0x9d, 0x22, 0xd5, 0x7e, 0x46, 0x9f, 0x47, 0x52, // FE::Graphics::ModelAssetManager (this type)
                0x8e, 0x72, 0x1d, 0x85, 0xb8, 0x82, 0x48, 0xe9,
                0xad, 0x6e, 0x2a, 0xc8, 0x0a, 0x52, 0x63, 0x2e, // FE::Graphics::IModelAssetManager
                0xe1, 0xe0, 0xbd, 0x22, 0x54, 0x3a, 0x40, 0x36,
                0xb9, 0x18, 0x13, 0x4d, 0xb9, 0xc9, 0x9d, 0x4f, // FE::IO::IAsyncReadCallback
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::IModelAssetManager*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::IO::IAsyncReadCallback*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 3 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_6ca86f0571ea45d89d22d57e469f4752()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ModelAssetManager::RTTI_GetType()
    {
        return RTTI_GetMutableType_6ca86f0571ea45d89d22d57e469f4752();
    }

    void* FE_VECTORCALL ModelAssetManager::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_6ca86f0571ea45d89d22d57e469f4752(this, typeID);
    }

    const void* FE_VECTORCALL ModelAssetManager::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_6ca86f0571ea45d89d22d57e469f4752(const_cast<ModelAssetManager*>(this), typeID);
    }

    void ModelAssetManager::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_6ca86f0571ea45d89d22d57e469f4752();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x6c, 0xa8, 0x6f, 0x05, 0x71, 0xea, 0x45, 0xd8,
            0x9d, 0x22, 0xd5, 0x7e, 0x46, 0x9f, 0x47, 0x52, // FE::Graphics::ModelAssetManager
        };

        static constexpr alignas(16) festd::array<uint8_t, 3 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x8e, 0x72, 0x1d, 0x85, 0xb8, 0x82, 0x48, 0xe9,
            0xad, 0x6e, 0x2a, 0xc8, 0x0a, 0x52, 0x63, 0x2e, // FE::Graphics::IModelAssetManager
            0xe1, 0xe0, 0xbd, 0x22, 0x54, 0x3a, 0x40, 0x36,
            0xb9, 0x18, 0x13, 0x4d, 0xb9, 0xc9, 0x9d, 0x4f, // FE::IO::IAsyncReadCallback
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<ModelAssetManager>(typeInstance,
                                                Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                "FE::Graphics::ModelAssetManager",
                                                kBaseClassTypeIDs,
                                                kAttributes,
                                                kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_6ca86f0571ea45d89d22d57e469f4752(&ModelAssetManager::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID SceneImpl::TypeID = Rtti::TypeID{ "75336687-960e-4693-ae02-a6dcda770fac" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_75336687960e4693ae02a6dcda770fac(SceneImpl* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x75, 0x33, 0x66, 0x87, 0x96, 0x0e, 0x46, 0x93,
                0xae, 0x02, 0xa6, 0xdc, 0xda, 0x77, 0x0f, 0xac, // FE::Graphics::SceneImpl (this type)
                0x20, 0x12, 0x1f, 0x05, 0x8d, 0x10, 0x44, 0x27,
                0x99, 0x25, 0x2d, 0xba, 0x38, 0x83, 0x79, 0xc9, // FE::Graphics::Scene
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::Scene*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_75336687960e4693ae02a6dcda770fac()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SceneImpl::RTTI_GetType()
    {
        return RTTI_GetMutableType_75336687960e4693ae02a6dcda770fac();
    }

    void* FE_VECTORCALL SceneImpl::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_75336687960e4693ae02a6dcda770fac(this, typeID);
    }

    const void* FE_VECTORCALL SceneImpl::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_75336687960e4693ae02a6dcda770fac(const_cast<SceneImpl*>(this), typeID);
    }

    void SceneImpl::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_75336687960e4693ae02a6dcda770fac();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x75, 0x33, 0x66, 0x87, 0x96, 0x0e, 0x46, 0x93,
            0xae, 0x02, 0xa6, 0xdc, 0xda, 0x77, 0x0f, 0xac, // FE::Graphics::SceneImpl
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x20, 0x12, 0x1f, 0x05, 0x8d, 0x10, 0x44, 0x27,
            0x99, 0x25, 0x2d, 0xba, 0x38, 0x83, 0x79, 0xc9, // FE::Graphics::Scene
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SceneImpl>(typeInstance,
                                        Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                        "FE::Graphics::SceneImpl",
                                        kBaseClassTypeIDs,
                                        kAttributes,
                                        kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_75336687960e4693ae02a6dcda770fac(&SceneImpl::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID SceneModuleBase::TypeID = Rtti::TypeID{ "7729e683-8638-4712-81d3-b1c78b16bfe3" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_7729e6838638471281d3b1c78b16bfe3(SceneModuleBase* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x77, 0x29, 0xe6, 0x83, 0x86, 0x38, 0x47, 0x12,
                0x81, 0xd3, 0xb1, 0xc7, 0x8b, 0x16, 0xbf, 0xe3, // FE::Graphics::SceneModuleBase (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_7729e6838638471281d3b1c78b16bfe3()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& SceneModuleBase::RTTI_GetType()
    {
        return RTTI_GetMutableType_7729e6838638471281d3b1c78b16bfe3();
    }

    void* FE_VECTORCALL SceneModuleBase::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_7729e6838638471281d3b1c78b16bfe3(this, typeID);
    }

    const void* FE_VECTORCALL SceneModuleBase::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_7729e6838638471281d3b1c78b16bfe3(const_cast<SceneModuleBase*>(this), typeID);
    }

    void SceneModuleBase::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_7729e6838638471281d3b1c78b16bfe3();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x77, 0x29, 0xe6, 0x83, 0x86, 0x38, 0x47, 0x12,
            0x81, 0xd3, 0xb1, 0xc7, 0x8b, 0x16, 0xbf, 0xe3, // FE::Graphics::SceneModuleBase
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<SceneModuleBase>(typeInstance,
                                              Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                              "FE::Graphics::SceneModuleBase",
                                              kBaseClassTypeIDs,
                                              kAttributes,
                                              kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_7729e6838638471281d3b1c78b16bfe3(&SceneModuleBase::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID ViewModuleBase::TypeID = Rtti::TypeID{ "77bc4de9-a792-4a65-bcb8-f23556551774" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_77bc4de9a7924a65bcb8f23556551774(ViewModuleBase* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x77, 0xbc, 0x4d, 0xe9, 0xa7, 0x92, 0x4a, 0x65,
                0xbc, 0xb8, 0xf2, 0x35, 0x56, 0x55, 0x17, 0x74, // FE::Graphics::ViewModuleBase (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_77bc4de9a7924a65bcb8f23556551774()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ViewModuleBase::RTTI_GetType()
    {
        return RTTI_GetMutableType_77bc4de9a7924a65bcb8f23556551774();
    }

    void* FE_VECTORCALL ViewModuleBase::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_77bc4de9a7924a65bcb8f23556551774(this, typeID);
    }

    const void* FE_VECTORCALL ViewModuleBase::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_77bc4de9a7924a65bcb8f23556551774(const_cast<ViewModuleBase*>(this), typeID);
    }

    void ViewModuleBase::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_77bc4de9a7924a65bcb8f23556551774();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x77, 0xbc, 0x4d, 0xe9, 0xa7, 0x92, 0x4a, 0x65,
            0xbc, 0xb8, 0xf2, 0x35, 0x56, 0x55, 0x17, 0x74, // FE::Graphics::ViewModuleBase
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<ViewModuleBase>(typeInstance,
                                             Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                             "FE::Graphics::ViewModuleBase",
                                             kBaseClassTypeIDs,
                                             kAttributes,
                                             kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_77bc4de9a7924a65bcb8f23556551774(&ViewModuleBase::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Rtti
{
    namespace
    {
        Type& GetMutableType_7fe0fa6fc0425f7db4b727b0929e813a()
        {
            static Type typeInstance;
            return typeInstance;
        }
    } // namespace

    template<>
    const Type& GetType<FE::Graphics::Tools::Blit::Constants>()
    {
        return GetMutableType_7fe0fa6fc0425f7db4b727b0929e813a();
    }

    template<>
    TypeID GetTypeID<FE::Graphics::Tools::Blit::Constants>()
    {
        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x7f, 0xe0, 0xfa, 0x6f, 0xc0, 0x42, 0x5f, 0x7d,
            0xb4, 0xb7, 0x27, 0xb0, 0x92, 0x9e, 0x81, 0x3a, // FE::Graphics::Tools::Blit::Constants
        };

        return TypeID::LoadAligned(kTypeIDBytes);
    }

    void Internal::ExternalTypeReflector<FE::Graphics::Tools::Blit::Constants>::Reflect(ReflectionContext& context)
    {
        Type& typeInstance = GetMutableType_7fe0fa6fc0425f7db4b727b0929e813a();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x7f, 0xe0, 0xfa, 0x6f, 0xc0, 0x42, 0x5f, 0x7d,
            0xb4, 0xb7, 0x27, 0xb0, 0x92, 0x9e, 0x81, 0x3a, // FE::Graphics::Tools::Blit::Constants
        };

        static constexpr alignas(16) uint8_t kFieldTypeIDs[5 * sizeof(TypeID)] = {
            0x25, 0xc9, 0x34, 0xe8, 0xed, 0x78, 0x41, 0xd5,
            0xb3, 0xe2, 0xe1, 0x3b, 0x97, 0xaf, 0xca, 0xc6, // FE::Vector2Base<float> m_uvOffset
            0x25, 0xc9, 0x34, 0xe8, 0xed, 0x78, 0x41, 0xd5,
            0xb3, 0xe2, 0xe1, 0x3b, 0x97, 0xaf, 0xca, 0xc6, // FE::Vector2Base<float> m_uvScale
            0x4b, 0x51, 0x72, 0xef, 0x1e, 0x7a, 0x43, 0xe2,
            0xb5, 0x89, 0x1b, 0xac, 0x65, 0x42, 0x8e, 0x92, // FE::Graphics::TextureSRVDescriptor m_input
            0x0a, 0xdc, 0x65, 0xde, 0x1b, 0xa6, 0x4a, 0x60,
            0xb3, 0x20, 0x33, 0x3a, 0xd0, 0xc2, 0xf2, 0x7b, // FE::Graphics::SamplerDescriptor m_sampler
            0x25, 0xc9, 0x34, 0xe8, 0xed, 0x78, 0x41, 0xd5,
            0xb3, 0xe2, 0xe1, 0x3b, 0x97, 0xaf, 0xca, 0xc6, // FE::Vector2Base<float> m_padding
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_uvOffset = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_uvScale = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_input = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_sampler = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_padding = {};

        static const festd::array<Rtti::FieldInfo, 5> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_uvOffset",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::Constants::m_uvOffset,
                                                        kAttributes_m_uvOffset,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_uvScale",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::Constants::m_uvScale,
                                                        kAttributes_m_uvScale,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_input",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::Constants::m_input,
                                                        kAttributes_m_input,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_sampler",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 3 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::Constants::m_sampler,
                                                        kAttributes_m_sampler,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_padding",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 4 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::Constants::m_padding,
                                                        kAttributes_m_padding,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<FE::Graphics::Tools::Blit::Constants>(typeInstance,
                                                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                                   "FE::Graphics::Tools::Blit::Constants",
                                                                   {},
                                                                   kAttributes,
                                                                   kFields);
    }

    static TypeRegistrar GTypeRegistrar_7fe0fa6fc0425f7db4b727b0929e813a(
        &Internal::ExternalTypeReflector<FE::Graphics::Tools::Blit::Constants>::Reflect);
} // namespace FE::Rtti


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Rtti
{
    namespace
    {
        Type& GetMutableType_829614c9c21e5177a303cf87676ecf08()
        {
            static Type typeInstance;
            return typeInstance;
        }
    } // namespace

    template<>
    const Type& GetType<FE::Graphics::Tools::Blit::PassDesc>()
    {
        return GetMutableType_829614c9c21e5177a303cf87676ecf08();
    }

    template<>
    TypeID GetTypeID<FE::Graphics::Tools::Blit::PassDesc>()
    {
        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x82, 0x96, 0x14, 0xc9, 0xc2, 0x1e, 0x51, 0x77,
            0xa3, 0x03, 0xcf, 0x87, 0x67, 0x6e, 0xcf, 0x08, // FE::Graphics::Tools::Blit::PassDesc
        };

        return TypeID::LoadAligned(kTypeIDBytes);
    }

    void Internal::ExternalTypeReflector<FE::Graphics::Tools::Blit::PassDesc>::Reflect(ReflectionContext& context)
    {
        Type& typeInstance = GetMutableType_829614c9c21e5177a303cf87676ecf08();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0x82, 0x96, 0x14, 0xc9, 0xc2, 0x1e, 0x51, 0x77,
            0xa3, 0x03, 0xcf, 0x87, 0x67, 0x6e, 0xcf, 0x08, // FE::Graphics::Tools::Blit::PassDesc
        };

        static constexpr alignas(16) uint8_t kFieldTypeIDs[3 * sizeof(TypeID)] = {
            0x7f, 0xe0, 0xfa, 0x6f, 0xc0, 0x42, 0x5f, 0x7d,
            0xb4, 0xb7, 0x27, 0xb0, 0x92, 0x9e, 0x81, 0x3a, // FE::Graphics::Tools::Blit::Constants m_constants
            0x1d, 0x24, 0x00, 0x0b, 0x33, 0xb4, 0x4b, 0xaf,
            0x88, 0x25, 0x96, 0x02, 0xcd, 0xb0, 0x8c, 0xc8, // FE::Graphics::Core::PassColorTarget m_colorTarget
            0xd9, 0x0e, 0xd8, 0x70, 0xc9, 0x66, 0x44, 0x3f,
            0x9b, 0xfe, 0x1d, 0x75, 0x3a, 0xee, 0xdf, 0xbf, // FE::Graphics::Core::PassGraphicsPipeline m_pipeline
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_constants = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_colorTarget = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_pipeline = {};

        static const festd::array<Rtti::FieldInfo, 3> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_constants",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::PassDesc::m_constants,
                                                        kAttributes_m_constants,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_colorTarget",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::PassDesc::m_colorTarget,
                                                        kAttributes_m_colorTarget,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_pipeline",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 2 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Blit::PassDesc::m_pipeline,
                                                        kAttributes_m_pipeline,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<FE::Graphics::Tools::Blit::PassDesc>(typeInstance,
                                                                  Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                                  "FE::Graphics::Tools::Blit::PassDesc",
                                                                  {},
                                                                  kAttributes,
                                                                  kFields);
    }

    static TypeRegistrar GTypeRegistrar_829614c9c21e5177a303cf87676ecf08(
        &Internal::ExternalTypeReflector<FE::Graphics::Tools::Blit::PassDesc>::Reflect);
} // namespace FE::Rtti


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID Renderer::TypeID = Rtti::TypeID{ "8666f778-3bbf-44cb-87b6-aa1c7b2089d7" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_8666f7783bbf44cb87b6aa1c7b2089d7(Renderer* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x86, 0x66, 0xf7, 0x78, 0x3b, 0xbf, 0x44, 0xcb,
                0x87, 0xb6, 0xaa, 0x1c, 0x7b, 0x20, 0x89, 0xd7, // FE::Graphics::Renderer (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_8666f7783bbf44cb87b6aa1c7b2089d7()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& Renderer::RTTI_GetType()
    {
        return RTTI_GetMutableType_8666f7783bbf44cb87b6aa1c7b2089d7();
    }

    void* FE_VECTORCALL Renderer::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_8666f7783bbf44cb87b6aa1c7b2089d7(this, typeID);
    }

    const void* FE_VECTORCALL Renderer::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_8666f7783bbf44cb87b6aa1c7b2089d7(const_cast<Renderer*>(this), typeID);
    }

    void Renderer::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_8666f7783bbf44cb87b6aa1c7b2089d7();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x86, 0x66, 0xf7, 0x78, 0x3b, 0xbf, 0x44, 0xcb,
            0x87, 0xb6, 0xaa, 0x1c, 0x7b, 0x20, 0x89, 0xd7, // FE::Graphics::Renderer
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<Renderer>(typeInstance,
                                       Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                       "FE::Graphics::Renderer",
                                       kBaseClassTypeIDs,
                                       kAttributes,
                                       kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_8666f7783bbf44cb87b6aa1c7b2089d7(&Renderer::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID MeshInstanceTable::TypeID = Rtti::TypeID{ "8a836070-a798-50fb-a93b-6fe5848b70b9" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_8a836070a79850fba93b6fe5848b70b9(MeshInstanceTable* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0x8a, 0x83, 0x60, 0x70, 0xa7, 0x98, 0x50, 0xfb,
                0xa9, 0x3b, 0x6f, 0xe5, 0x84, 0x8b, 0x70, 0xb9, // FE::Graphics::MeshInstanceTable (this type)
                0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
                0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::DB::TableBase*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_8a836070a79850fba93b6fe5848b70b9()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& MeshInstanceTable::RTTI_GetType()
    {
        return RTTI_GetMutableType_8a836070a79850fba93b6fe5848b70b9();
    }

    void* FE_VECTORCALL MeshInstanceTable::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_8a836070a79850fba93b6fe5848b70b9(this, typeID);
    }

    const void* FE_VECTORCALL MeshInstanceTable::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_8a836070a79850fba93b6fe5848b70b9(const_cast<MeshInstanceTable*>(this), typeID);
    }

    void MeshInstanceTable::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_8a836070a79850fba93b6fe5848b70b9();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x8a, 0x83, 0x60, 0x70, 0xa7, 0x98, 0x50, 0xfb,
            0xa9, 0x3b, 0x6f, 0xe5, 0x84, 0x8b, 0x70, 0xb9, // FE::Graphics::MeshInstanceTable
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
            0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<MeshInstanceTable>(typeInstance,
                                                Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                "FE::Graphics::MeshInstanceTable",
                                                kBaseClassTypeIDs,
                                                kAttributes,
                                                kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_8a836070a79850fba93b6fe5848b70b9(&MeshInstanceTable::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID IModelAssetManager::TypeID = Rtti::TypeID{ "8e721d85-b882-48e9-ad6e-2ac80a52632e" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_8e721d85b88248e9ad6e2ac80a52632e(IModelAssetManager* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0x8e, 0x72, 0x1d, 0x85, 0xb8, 0x82, 0x48, 0xe9,
                0xad, 0x6e, 0x2a, 0xc8, 0x0a, 0x52, 0x63, 0x2e, // FE::Graphics::IModelAssetManager (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_8e721d85b88248e9ad6e2ac80a52632e()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& IModelAssetManager::RTTI_GetType()
    {
        return RTTI_GetMutableType_8e721d85b88248e9ad6e2ac80a52632e();
    }

    void* FE_VECTORCALL IModelAssetManager::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_8e721d85b88248e9ad6e2ac80a52632e(this, typeID);
    }

    const void* FE_VECTORCALL IModelAssetManager::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_8e721d85b88248e9ad6e2ac80a52632e(const_cast<IModelAssetManager*>(this), typeID);
    }

    void IModelAssetManager::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_8e721d85b88248e9ad6e2ac80a52632e();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x8e, 0x72, 0x1d, 0x85, 0xb8, 0x82, 0x48, 0xe9,
            0xad, 0x6e, 0x2a, 0xc8, 0x0a, 0x52, 0x63, 0x2e, // FE::Graphics::IModelAssetManager
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<IModelAssetManager>(typeInstance,
                                                 Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                 "FE::Graphics::IModelAssetManager",
                                                 kBaseClassTypeIDs,
                                                 kAttributes,
                                                 kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_8e721d85b88248e9ad6e2ac80a52632e(&IModelAssetManager::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID TextureAssetManager::TypeID = Rtti::TypeID{ "9bc819e7-f2cd-47d3-a84c-421cef60fc98" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_9bc819e7f2cd47d3a84c421cef60fc98(TextureAssetManager* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[4 * sizeof(Rtti::TypeID)] = {
                0x9b, 0xc8, 0x19, 0xe7, 0xf2, 0xcd, 0x47, 0xd3,
                0xa8, 0x4c, 0x42, 0x1c, 0xef, 0x60, 0xfc, 0x98, // FE::Graphics::TextureAssetManager (this type)
                0xde, 0x91, 0x93, 0x40, 0x61, 0xe9, 0x46, 0x7e,
                0x96, 0xcb, 0xca, 0xf0, 0x37, 0xa2, 0x0a, 0x3a, // FE::Graphics::ITextureAssetManager
                0xe1, 0xe0, 0xbd, 0x22, 0x54, 0x3a, 0x40, 0x36,
                0xb9, 0x18, 0x13, 0x4d, 0xb9, 0xc9, 0x9d, 0x4f, // FE::IO::IAsyncReadCallback
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::ITextureAssetManager*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::IO::IAsyncReadCallback*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 3 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_9bc819e7f2cd47d3a84c421cef60fc98()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& TextureAssetManager::RTTI_GetType()
    {
        return RTTI_GetMutableType_9bc819e7f2cd47d3a84c421cef60fc98();
    }

    void* FE_VECTORCALL TextureAssetManager::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_9bc819e7f2cd47d3a84c421cef60fc98(this, typeID);
    }

    const void* FE_VECTORCALL TextureAssetManager::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_9bc819e7f2cd47d3a84c421cef60fc98(const_cast<TextureAssetManager*>(this), typeID);
    }

    void TextureAssetManager::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_9bc819e7f2cd47d3a84c421cef60fc98();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0x9b, 0xc8, 0x19, 0xe7, 0xf2, 0xcd, 0x47, 0xd3,
            0xa8, 0x4c, 0x42, 0x1c, 0xef, 0x60, 0xfc, 0x98, // FE::Graphics::TextureAssetManager
        };

        static constexpr alignas(16) festd::array<uint8_t, 3 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xde, 0x91, 0x93, 0x40, 0x61, 0xe9, 0x46, 0x7e,
            0x96, 0xcb, 0xca, 0xf0, 0x37, 0xa2, 0x0a, 0x3a, // FE::Graphics::ITextureAssetManager
            0xe1, 0xe0, 0xbd, 0x22, 0x54, 0x3a, 0x40, 0x36,
            0xb9, 0x18, 0x13, 0x4d, 0xb9, 0xc9, 0x9d, 0x4f, // FE::IO::IAsyncReadCallback
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<TextureAssetManager>(typeInstance,
                                                  Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                  "FE::Graphics::TextureAssetManager",
                                                  kBaseClassTypeIDs,
                                                  kAttributes,
                                                  kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_9bc819e7f2cd47d3a84c421cef60fc98(&TextureAssetManager::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Rtti
{
    namespace
    {
        Type& GetMutableType_ade5a371ffc255fcb893591a7d181eb2()
        {
            static Type typeInstance;
            return typeInstance;
        }
    } // namespace

    template<>
    const Type& GetType<FE::Graphics::Tools::Downsample::PassDesc>()
    {
        return GetMutableType_ade5a371ffc255fcb893591a7d181eb2();
    }

    template<>
    TypeID GetTypeID<FE::Graphics::Tools::Downsample::PassDesc>()
    {
        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0xad, 0xe5, 0xa3, 0x71, 0xff, 0xc2, 0x55, 0xfc,
            0xb8, 0x93, 0x59, 0x1a, 0x7d, 0x18, 0x1e, 0xb2, // FE::Graphics::Tools::Downsample::PassDesc
        };

        return TypeID::LoadAligned(kTypeIDBytes);
    }

    void Internal::ExternalTypeReflector<FE::Graphics::Tools::Downsample::PassDesc>::Reflect(ReflectionContext& context)
    {
        Type& typeInstance = GetMutableType_ade5a371ffc255fcb893591a7d181eb2();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(TypeID)] = {
            0xad, 0xe5, 0xa3, 0x71, 0xff, 0xc2, 0x55, 0xfc,
            0xb8, 0x93, 0x59, 0x1a, 0x7d, 0x18, 0x1e, 0xb2, // FE::Graphics::Tools::Downsample::PassDesc
        };

        static constexpr alignas(16) uint8_t kFieldTypeIDs[2 * sizeof(TypeID)] = {
            0x1f, 0x7c, 0x86, 0xca, 0x9d, 0xfb, 0x57, 0x09,
            0xa3, 0xe6, 0xfc, 0xf1, 0x14, 0xc5, 0x71, 0xe6, // FE::Graphics::Tools::Downsample::Constants m_constants
            0xbd, 0xe9, 0xab, 0x4a, 0xd5, 0x06, 0x4b, 0x19,
            0x96, 0x12, 0x3f, 0xb7, 0xe5, 0x13, 0x3e, 0xea, // FE::Graphics::Core::PassComputePipeline m_pipeline
        };
        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_constants = {};

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes_m_pipeline = {};

        static const festd::array<Rtti::FieldInfo, 2> kFields = {
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_constants",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 0 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::PassDesc::m_constants,
                                                        kAttributes_m_constants,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
            Rtti::ReflectionContext::CreateFieldInfo<1>("m_pipeline",
                                                        TypeID::LoadAligned(kFieldTypeIDs + 1 * sizeof(TypeID)),
                                                        &FE::Graphics::Tools::Downsample::PassDesc::m_pipeline,
                                                        kAttributes_m_pipeline,
                                                        Rtti::FieldFlags::kInstance | Rtti::FieldFlags::kPublic),
        };

        context.ReflectClass<FE::Graphics::Tools::Downsample::PassDesc>(typeInstance,
                                                                        Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                                        "FE::Graphics::Tools::Downsample::PassDesc",
                                                                        {},
                                                                        kAttributes,
                                                                        kFields);
    }

    static TypeRegistrar GTypeRegistrar_ade5a371ffc255fcb893591a7d181eb2(
        &Internal::ExternalTypeReflector<FE::Graphics::Tools::Downsample::PassDesc>::Reflect);
} // namespace FE::Rtti


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics::DB
{
    const Rtti::TypeID TableBase::TypeID = Rtti::TypeID{ "b0b29217-3d30-4b35-8026-9d0eb91b8fd2" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_b0b292173d304b3580269d0eb91b8fd2(TableBase* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
                0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_b0b292173d304b3580269d0eb91b8fd2()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& TableBase::RTTI_GetType()
    {
        return RTTI_GetMutableType_b0b292173d304b3580269d0eb91b8fd2();
    }

    void* FE_VECTORCALL TableBase::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_b0b292173d304b3580269d0eb91b8fd2(this, typeID);
    }

    const void* FE_VECTORCALL TableBase::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_b0b292173d304b3580269d0eb91b8fd2(const_cast<TableBase*>(this), typeID);
    }

    void TableBase::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_b0b292173d304b3580269d0eb91b8fd2();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xb0, 0xb2, 0x92, 0x17, 0x3d, 0x30, 0x4b, 0x35,
            0x80, 0x26, 0x9d, 0x0e, 0xb9, 0x1b, 0x8f, 0xd2, // FE::Graphics::DB::TableBase
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<TableBase>(typeInstance,
                                        Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                        "FE::Graphics::DB::TableBase",
                                        kBaseClassTypeIDs,
                                        kAttributes,
                                        kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_b0b292173d304b3580269d0eb91b8fd2(&TableBase::Reflect);
} // namespace FE::Graphics::DB


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID RendererImpl::TypeID = Rtti::TypeID{ "cfd1e397-fc2e-4f9b-99f3-4cf67f695b1e" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_cfd1e397fc2e4f9b99f34cf67f695b1e(RendererImpl* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[3 * sizeof(Rtti::TypeID)] = {
                0xcf, 0xd1, 0xe3, 0x97, 0xfc, 0x2e, 0x4f, 0x9b,
                0x99, 0xf3, 0x4c, 0xf6, 0x7f, 0x69, 0x5b, 0x1e, // FE::Graphics::RendererImpl (this type)
                0x86, 0x66, 0xf7, 0x78, 0x3b, 0xbf, 0x44, 0xcb,
                0x87, 0xb6, 0xaa, 0x1c, 0x7b, 0x20, 0x89, 0xd7, // FE::Graphics::Renderer
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Graphics::Renderer*>(thisPtr);
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 2 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_cfd1e397fc2e4f9b99f34cf67f695b1e()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& RendererImpl::RTTI_GetType()
    {
        return RTTI_GetMutableType_cfd1e397fc2e4f9b99f34cf67f695b1e();
    }

    void* FE_VECTORCALL RendererImpl::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_cfd1e397fc2e4f9b99f34cf67f695b1e(this, typeID);
    }

    const void* FE_VECTORCALL RendererImpl::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_cfd1e397fc2e4f9b99f34cf67f695b1e(const_cast<RendererImpl*>(this), typeID);
    }

    void RendererImpl::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_cfd1e397fc2e4f9b99f34cf67f695b1e();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xcf, 0xd1, 0xe3, 0x97, 0xfc, 0x2e, 0x4f, 0x9b,
            0x99, 0xf3, 0x4c, 0xf6, 0x7f, 0x69, 0x5b, 0x1e, // FE::Graphics::RendererImpl
        };

        static constexpr alignas(16) festd::array<uint8_t, 2 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0x86, 0x66, 0xf7, 0x78, 0x3b, 0xbf, 0x44, 0xcb,
            0x87, 0xb6, 0xaa, 0x1c, 0x7b, 0x20, 0x89, 0xd7, // FE::Graphics::Renderer
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<RendererImpl>(typeInstance,
                                           Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                           "FE::Graphics::RendererImpl",
                                           kBaseClassTypeIDs,
                                           kAttributes,
                                           kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_cfd1e397fc2e4f9b99f34cf67f695b1e(&RendererImpl::Reflect);
} // namespace FE::Graphics


#include <FeCore/RTTI/ReflectionContext.h>

namespace FE::Graphics
{
    const Rtti::TypeID ITextureAssetManager::TypeID = Rtti::TypeID{ "de919340-61e9-467e-96cb-caf037a20a3a" };

    namespace
    {
        FE_FORCE_INLINE void* FE_VECTORCALL RTTI_TryCastImpl_de91934061e9467e96cbcaf037a20a3a(ITextureAssetManager* thisPtr,
                                                                                              const Rtti::TypeID typeID)
        {
            static constexpr alignas(16) uint8_t kBaseClassTypeIDs[2 * sizeof(Rtti::TypeID)] = {
                0xde, 0x91, 0x93, 0x40, 0x61, 0xe9, 0x46, 0x7e,
                0x96, 0xcb, 0xca, 0xf0, 0x37, 0xa2, 0x0a, 0x3a, // FE::Graphics::ITextureAssetManager (this type)
                0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
                0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
            };

            __m128i id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs));
            __m128i mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return thisPtr;
            id = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kBaseClassTypeIDs + 1 * sizeof(Rtti::TypeID)));
            mask = _mm_cmpeq_epi8(id, typeID.m_simdVector);
            if (_mm_movemask_epi8(mask) == 0xffff)
                return static_cast<FE::Memory::RefCountedObjectBase*>(thisPtr);

            return nullptr;
        }

        Rtti::Type& RTTI_GetMutableType_de91934061e9467e96cbcaf037a20a3a()
        {
            static Rtti::Type typeInstance;
            return typeInstance;
        }
    } // namespace

    const Rtti::Type& ITextureAssetManager::RTTI_GetType()
    {
        return RTTI_GetMutableType_de91934061e9467e96cbcaf037a20a3a();
    }

    void* FE_VECTORCALL ITextureAssetManager::RTTI_TryCast(const Rtti::TypeID typeID)
    {
        return RTTI_TryCastImpl_de91934061e9467e96cbcaf037a20a3a(this, typeID);
    }

    const void* FE_VECTORCALL ITextureAssetManager::RTTI_TryCast(const Rtti::TypeID typeID) const
    {
        return RTTI_TryCastImpl_de91934061e9467e96cbcaf037a20a3a(const_cast<ITextureAssetManager*>(this), typeID);
    }

    void ITextureAssetManager::Reflect(Rtti::ReflectionContext& context)
    {
        Rtti::Type& typeInstance = RTTI_GetMutableType_de91934061e9467e96cbcaf037a20a3a();

        static constexpr alignas(16) uint8_t kTypeIDBytes[sizeof(Rtti::TypeID)] = {
            0xde, 0x91, 0x93, 0x40, 0x61, 0xe9, 0x46, 0x7e,
            0x96, 0xcb, 0xca, 0xf0, 0x37, 0xa2, 0x0a, 0x3a, // FE::Graphics::ITextureAssetManager
        };

        static constexpr alignas(16) festd::array<uint8_t, 1 * sizeof(Rtti::TypeID)> kBaseClassTypeIDs = {
            0xb4, 0xfa, 0x5c, 0x63, 0x69, 0xc0, 0x46, 0x66,
            0x8a, 0x92, 0x72, 0x6f, 0x07, 0x0d, 0x76, 0x9b, // FE::Memory::RefCountedObjectBase
        };

        static constexpr festd::array<Rtti::Attribute, 0> kAttributes = {};

        static const festd::array<Rtti::FieldInfo, 0> kFields = {};

        context.ReflectClass<ITextureAssetManager>(typeInstance,
                                                   Rtti::TypeID::LoadAligned(kTypeIDBytes),
                                                   "FE::Graphics::ITextureAssetManager",
                                                   kBaseClassTypeIDs,
                                                   kAttributes,
                                                   kFields);
    }

    static Rtti::TypeRegistrar GTypeRegistrar_de91934061e9467e96cbcaf037a20a3a(&ITextureAssetManager::Reflect);
} // namespace FE::Graphics
