//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Shaders/Database/Base.hlsli>
#include <Shaders/Tables/Forwards.hlsli>

struct MeshBatchTable
{
    FE_CONSTEXPR uint32_t kRowsPerPage = DB::kTablePageSize / (sizeof(DB::Slice<MeshMemberTable>) + sizeof(uint32_t));

    FE_CONSTEXPR uint32_t kOffset_m_members = 0;
    FE_CONSTEXPR uint32_t kOffset_m_passMask = kOffset_m_members + sizeof(DB::Slice<MeshMemberTable>) * kRowsPerPage;

    struct Row
    {
        DB::ElementHandle<DB::Slice<MeshMemberTable>, kOffset_m_members> m_members;
        DB::ElementHandle<uint32_t, kOffset_m_passMask> m_passMask;
    };

    struct Instance
    {
        BufferPointer m_pageTableAddress;
    };

    static MeshBatchTable Create(Instance instance)
    {
        MeshBatchTable table;
        table.m_pageTableAddress = instance.m_pageTableAddress;
        return table;
    }

    Row ReadRow(const uint32_t rowIndex)
    {
        const uint32_t pageIndex = rowIndex / kRowsPerPage;
        const uint32_t localRowIndex = rowIndex % kRowsPerPage;

        const BufferPointer pageAddress = m_pageTableAddress.Read<BufferPointer>(pageIndex * sizeof(BufferPointer));

        Row row;
        row.m_members.Setup(pageAddress, localRowIndex);
        row.m_passMask.Setup(pageAddress, localRowIndex);
        return row;
    }

    Row ReadRow(const DB::Ref<MeshBatchTable> reference)
    {
        return ReadRow(reference.m_rowIndex);
    }

    BufferPointer m_pageTableAddress;
};
