//
// This file was generated by Ferrum3D Code Generator.
// Manual changes will be lost.
//

#pragma once
#include <Shaders/Database/Base.hlsli>
#include <Shaders/Tables/Forwards.hlsli>

struct MeshMemberTable
{
    FE_CONSTEXPR uint32_t kRowsPerPage = DB::kTablePageSize / (sizeof(DB::Ref<MeshInstanceTable>));

    FE_CONSTEXPR uint32_t kOffset_m_instance = 0;

    struct Row
    {
        DB::ElementHandle<DB::Ref<MeshInstanceTable>, kOffset_m_instance> m_instance;
    };

    struct Instance
    {
        BufferPointer m_pageTableAddress;
    };

    static MeshMemberTable Create(Instance instance)
    {
        MeshMemberTable table;
        table.m_pageTableAddress = instance.m_pageTableAddress;
        return table;
    }

    Row ReadRow(const uint32_t rowIndex)
    {
        const uint32_t pageIndex = rowIndex / kRowsPerPage;
        const uint32_t localRowIndex = rowIndex % kRowsPerPage;

        const BufferPointer pageAddress = m_pageTableAddress.Read<BufferPointer>(pageIndex * sizeof(BufferPointer));

        Row row;
        row.m_instance.Setup(pageAddress, localRowIndex);
        return row;
    }

    Row ReadRow(const DB::Ref<MeshMemberTable> reference)
    {
        return ReadRow(reference.m_rowIndex);
    }

    BufferPointer m_pageTableAddress;
};
